"""Terminal window title — the state contract, the sanitiser, and the writes.

Three properties are load-bearing and none of them is visible in the app's own
frame (the title is drawn by the terminal, outside anything Textual paints),
so they are pinned here rather than eyeballed:

- **The separator carries the run state.** ``›`` idle, a braille frame while
  working, ``!`` while the turn is parked on the user. A switcher clips the
  title, so the state has to survive in the leftmost cells.
- **Nothing reaches the wire that a model chose.** Conversation names are
  model-generated and an OSC string is terminated by BEL — a name carrying one
  would end the sequence early and leave the rest being read as terminal
  commands.
- **A repeat writes zero bytes.** The band repaints 12.5 times a second for
  the whole of a turn and re-asserts the same title on every idle repaint too.
"""

from __future__ import annotations

from typing import cast

from textual.widgets import Static

from local_operator.tui.terminal_title import (
    BRAND,
    MAX_LABEL_CHARS,
    POP_TITLE,
    PUSH_TITLE,
    SEP_ATTENTION,
    SEP_IDLE,
    SPINNER_FRAMES,
    TerminalTitle,
    build_title,
    cwd_label,
    osc_title,
    sanitize_label,
    terminal_title_enabled,
)
from local_operator.tui.widgets.status_line import StatusLine, SubagentBand
from tests.unit.tui.test_status_line import FakeDock


class Sink:
    """Collects what the app would have written to the terminal."""

    def __init__(self) -> None:
        self.writes: list[str] = []

    def __call__(self, data: str) -> None:
        self.writes.append(data)

    @property
    def titles(self) -> list[str]:
        """Just the OSC 0 payloads, in order — what a switcher would show."""
        return [
            data.removeprefix("\x1b]0;").removesuffix("\x07")
            for data in self.writes
            if data.startswith("\x1b]0;")
        ]


# -- the state contract ------------------------------------------------------


def test_idle_title_is_the_brand_a_chevron_and_the_name() -> None:
    assert (
        build_title("Reduce agent RAM usage", "idle")
        == f"{BRAND} {SEP_IDLE} Reduce agent RAM usage"
    )


def test_working_title_steps_through_the_spinner() -> None:
    """The separator IS the animation; the rest of the title holds still."""
    frames = [build_title("Fix quota reporting", "working", frame) for frame in range(10)]
    separators = [title.split(" ")[1] for title in frames]
    assert separators[: len(SPINNER_FRAMES)] == list(SPINNER_FRAMES)
    # Frame 8 wraps to frame 0: the index is the band's raw counter, which is
    # only modulo'd by the band when IT feels like it.
    assert separators[8] == SPINNER_FRAMES[0]
    assert all(title.endswith(" Fix quota reporting") for title in frames)


def test_attention_title_uses_the_app_wide_alarm_mark() -> None:
    assert (
        build_title("Triage sanctions", "attention") == f"{BRAND} {SEP_ATTENTION} Triage sanctions"
    )


def test_state_survives_when_there_is_no_name() -> None:
    """A nameless session still says whether it is running.

    The separator is the half a clipped sidebar row can always show, and
    dropping it would make a live turn indistinguishable from a finished one.
    """
    assert build_title("", "idle") == f"{BRAND} {SEP_IDLE}"
    assert build_title("", "working", 2) == f"{BRAND} {SPINNER_FRAMES[2]}"
    assert build_title("   ", "attention") == f"{BRAND} {SEP_ATTENTION}"


# -- the sanitiser -----------------------------------------------------------


def test_control_characters_are_stripped_from_a_model_written_name() -> None:
    """The security property: no name can close the OSC string early.

    BEL terminates OSC 0, and ESC opens a new sequence. A conversation title
    is generated by a model from the user's own prompt, so both are reachable
    by a prompt that quotes terminal output.
    """
    hostile = "Fix \x07 the\x1b]0;pwned\x07 parser"
    assert "\x07" not in sanitize_label(hostile)
    assert "\x1b" not in sanitize_label(hostile)
    # What survives is inert TEXT: the ESC is gone, so `]0;` is three
    # characters the terminal prints rather than the head of a sequence.
    assert sanitize_label(hostile) == "Fix the ]0;pwned parser"


def test_whitespace_is_collapsed_so_a_title_stays_one_line() -> None:
    assert sanitize_label("  two\n\nlines\tapart ") == "two lines apart"


def test_a_label_that_sanitizes_away_reads_as_no_label() -> None:
    assert sanitize_label("\x00\x1b\x07") == ""
    assert sanitize_label(None) == ""


def test_the_label_is_capped() -> None:
    # One enormous token has no boundary to cut on, so it is cut mid-token
    # rather than dropped — a tab reading `lo ›` says less than a cut string.
    # The ellipsis rides in the last cell, so the cap still holds exactly.
    assert len(sanitize_label("x" * 500)) == MAX_LABEL_CHARS


def test_an_over_long_label_is_cut_on_a_word_with_an_ellipsis() -> None:
    """The tab agrees with the band about how a long name is shortened.

    A bare slice ended the tab mid-word (`…and reconcile the ledge`), which
    reads as a string that ran out of buffer rather than as a name that was
    shortened — and the tab is where it bites hardest, since most terminals
    shorten the label again to fit the tab strip. Both the band
    (``status_line.truncate_name``) and the excerpt this string came from
    (``naming.provisional_title``) cut on a word, so this is parity rather than
    a new rule (design review D3).
    """
    label = sanitize_label(
        "Investigate why the nightly importer drops rows silently "
        "and reconcile the ledger totals"
    )
    assert len(label) <= MAX_LABEL_CHARS
    assert label.endswith("…")
    assert label == "Investigate why the nightly importer drops rows silently and reconcile the…"
    # A name that already fits is returned untouched — no stray ellipsis.
    assert sanitize_label("Reduce agent RAM usage") == "Reduce agent RAM usage"


def test_cwd_stands_in_for_a_conversation_that_has_no_name_yet() -> None:
    """Naming happens off the first substantive prompt, so every session
    spends its opening minutes unnamed — the case this feature is for."""
    assert cwd_label("/Users/tester/work/local-operator") == "local-operator"
    assert cwd_label("") == ""
    # A filesystem root has no basename worth showing: `lo › /` says less
    # than `lo ›`.
    assert cwd_label("/") == ""


# -- the writer --------------------------------------------------------------


def test_start_saves_the_terminals_own_title_before_painting_ours() -> None:
    """Order matters, not just presence: a title painted before the save is
    the title the terminal saves, and exit would then restore this session's
    name into the user's shell."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.set_label("Handle Lisa's billing thread")
    title.start()
    assert sink.writes[0] == PUSH_TITLE
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} Handle Lisa's billing thread"


def test_nothing_is_painted_before_the_save() -> None:
    """The band is populated (model, cwd) before the app attaches a writer, so
    setters genuinely do run ahead of ``start``."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.set_label("Set before start")
    title.set_state("working")
    assert sink.writes == []


def test_stop_gives_the_terminal_its_title_back_exactly_once() -> None:
    """A session that exits leaving its name in the user's shell tab is worse
    than one that never set it."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.start()
    title.stop()
    title.stop()
    assert sink.writes.count(POP_TITLE) == 1


def test_stop_without_start_restores_nothing() -> None:
    """The pair is balanced by the object, not by the caller's symmetry: an
    unmatched restore pops a title this process never pushed."""
    sink = Sink()
    TerminalTitle(sink).stop()
    assert sink.writes == []


def test_an_unchanged_title_writes_no_bytes() -> None:
    """The spinner ticks 12.5 times a second and every band repaint re-asserts
    the same state; without coalescing an IDLE session would write forever."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.start()
    before = len(sink.writes)
    for _ in range(50):
        title.set_label("Same name")
        title.set_state("idle")
        title.emit()
    assert len(sink.writes) == before + 1  # the one real change: the label


def test_frames_do_not_write_while_idle() -> None:
    """The band's spinner index keeps moving after a turn ends (it is only
    stopped, not reset by the timer), and an idle title must not follow it."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.start()
    before = len(sink.writes)
    for frame in range(1, 8):
        title.set_frame(frame)
    assert len(sink.writes) == before


def test_leaving_working_restarts_the_animation_from_the_top() -> None:
    """A spinner that resumes mid-sequence on the next turn looks like it
    never stopped."""
    sink = Sink()
    title = TerminalTitle(sink)
    title.start()
    title.set_state("working")
    title.set_frame(5)
    title.set_state("idle")
    title.set_state("working")
    assert title.current.split(" ")[1] == SPINNER_FRAMES[0]


def test_a_disabled_title_writes_nothing_at_all() -> None:
    """Off is a null object, not an ``Optional`` at every call site."""
    sink = Sink()
    title = TerminalTitle(sink, enabled=False)
    title.start()
    title.set_label("Anything")
    title.set_state("working")
    title.stop()
    assert sink.writes == []


def test_osc_0_sets_both_the_icon_name_and_the_window_title() -> None:
    """OSC 0, not OSC 2: tabbed terminals and multiplexers read the ICON name
    for a tab label, which is the surface this feature is aimed at."""
    assert osc_title("lo › x") == "\x1b]0;lo › x\x07"


def test_the_env_kill_switch_turns_the_feature_off(monkeypatch) -> None:  # noqa: ANN001
    monkeypatch.setenv("LOCAL_OPERATOR_NO_TERMINAL_TITLE", "1")
    assert terminal_title_enabled() is False


# -- driven by the status band ----------------------------------------------


def _banded() -> tuple[StatusLine, Sink, TerminalTitle]:
    """A band with a title attached, as the app wires it in ``on_mount``."""
    status = StatusLine(cast(Static, FakeDock(120)))
    sink = Sink()
    title = TerminalTitle(sink)
    title.start()
    status.set_terminal_title(title)
    return status, sink, title


def test_the_band_names_the_title_from_the_conversation() -> None:
    status, sink, _ = _banded()
    status.update(conversation_name="Reduce agent RAM usage")
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} Reduce agent RAM usage"


def test_an_unnamed_session_is_titled_with_its_directory() -> None:
    status, sink, _ = _banded()
    status.update(cwd="/Users/tester/work/minervaai")
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} minervaai"


def test_a_name_supersedes_the_directory_fallback() -> None:
    status, sink, _ = _banded()
    status.update(cwd="/Users/tester/work/minervaai")
    status.update(conversation_name="Triage sanctions regression")
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} Triage sanctions regression"


def test_streaming_turns_the_separator_into_the_spinner() -> None:
    status, sink, _ = _banded()
    status.update(conversation_name="Fix quota reporting", streaming=True)
    assert sink.titles[-1] == f"{BRAND} {SPINNER_FRAMES[0]} Fix quota reporting"
    status.update(streaming=False)
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} Fix quota reporting"


def test_the_titles_spinner_steps_with_the_bands() -> None:
    """One sequence, one cadence: in a tiled terminal both indicators are on
    screen at once, and two braille animations out of phase read as two
    separate things happening."""
    status, sink, _ = _banded()
    status.update(conversation_name="Fix quota reporting", streaming=True)
    status._advance_spinner()
    status._advance_spinner()
    assert sink.titles[-1] == f"{BRAND} {SPINNER_FRAMES[2]} Fix quota reporting"


def test_a_new_turn_restarts_the_title_spinner_from_frame_zero() -> None:
    """Streaming → idle → streaming must not flash the old turn's last frame.

    This is the real wiring path, not the pure ``TerminalTitle`` test: the band
    keeps its own spinner index and pushes it into the title on every refresh,
    which is where the stale-frame flash lived.
    """
    status, sink, _ = _banded()
    status.update(conversation_name="Fix quota reporting", streaming=True)
    status._advance_spinner()
    status._advance_spinner()
    assert sink.titles[-1] == f"{BRAND} {SPINNER_FRAMES[2]} Fix quota reporting"
    status.update(streaming=False)
    status.update(streaming=True)
    assert sink.titles[-1] == f"{BRAND} {SPINNER_FRAMES[0]} Fix quota reporting"


def test_attention_outranks_streaming() -> None:
    """A turn parked on an approval IS streaming; showing it as working is how
    a session the user needs to answer gets left alone."""
    status, sink, _ = _banded()
    status.update(conversation_name="Deploy the migration", streaming=True)
    status.set_attention(True)
    assert sink.titles[-1] == f"{BRAND} {SEP_ATTENTION} Deploy the migration"
    status.set_attention(False)
    assert sink.titles[-1].startswith(f"{BRAND} {SPINNER_FRAMES[0]}")


def test_a_subagent_page_titles_the_window_with_the_child() -> None:
    """Everything else in the band is the child's while its page is up; a
    title naming the parent would be the one contradicting label on screen."""
    status, sink, _ = _banded()
    status.update(conversation_name="Parent conversation")
    status.set_subagent(SubagentBand(label="reviewer", cost="$0.12"))
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} reviewer"
    status.set_subagent(None)
    assert sink.titles[-1] == f"{BRAND} {SEP_IDLE} Parent conversation"


def test_detaching_the_title_leaves_the_band_working() -> None:
    """The lightweight test hosts and any headless run have no terminal; the
    band must not require one."""
    status, sink, title = _banded()
    status.set_terminal_title(None)
    written = len(sink.writes)
    status.update(conversation_name="Nothing should be written", streaming=True)
    status._advance_spinner()
    assert len(sink.writes) == written
    assert title.current == f"{BRAND} {SEP_IDLE}"
