"""The portal build's bound: a bound that leaves a fork bomb running is not one.

WHY THESE EXIST
---------------
``_build_bundle`` used to run each step as ``subprocess.run(..., timeout=600)``,
which bounds the DIRECT CHILD only. When the bound fires, Python kills the leader
and returns, and everything the leader forked keeps running — and, in the shape
that took a machine down on 2026-09-21, keeps SPAWNING. A fresh clone's portal
build reached it through a ``packageManager`` pin the global pnpm did not match:
pnpm resolves such a pin by installing that pnpm WITH pnpm, so the tree grew back
after the first kill (+100 processes and +5 GB every 25 s) until the host had
0.1 GB free and no swap, and was rebooted.

TWO GUARDS, ONE INCIDENT. The step now runs in its own process group and the
GROUP is signalled on the bound, on an abort, and after an ordinary exit; and a
runner whose reported version is not the pinned one is refused before any pnpm
process starts. Both are exercised here.

The defect IS a process-tree behaviour, so no amount of mocking would be
evidence: each test plants a grandchild whose command line carries a unique
token (a pnpm stand-in does the forking) and asserts on what is ALIVE afterwards
— the same instrument the field observation used (``pgrep -f``). The first three
tests fail on the pre-fix tree, where the survivor they assert against is exactly
what the old code left behind; the PR carries the base-run output.
"""

from __future__ import annotations

import json
import os
import signal
import subprocess
import sys
import time
import uuid
from pathlib import Path
from typing import Iterator

import pytest

from local_operator.mobile import install

#: These spawn real processes and wait on real signals; the suite marks that
#: shape `slow` (see pyproject.toml's marker list).
pytestmark = pytest.mark.slow


def _token() -> str:
    """A marker that appears ONLY in a planted descendant's command line."""
    return f"bundle-bound-test-{uuid.uuid4().hex}"


def _pids_carrying(token: str) -> list[int]:
    """Every process whose command line carries ``token``, orphans included.

    ``pgrep -f`` is the instrument the incident was observed with, and unlike a
    ``ps --ppid`` walk it sees a process that has been re-parented — which is
    what a leaked descendant becomes.
    """
    result = subprocess.run(["pgrep", "-f", token], capture_output=True, text=True, check=False)
    return [int(line) for line in result.stdout.split() if line.strip()]


def _wait_until_gone(token: str, timeout: float = 15.0) -> list[int]:
    """The pids still carrying ``token`` once the tree should be dead."""
    deadline = time.monotonic() + timeout
    remaining = _pids_carrying(token)
    while remaining and time.monotonic() < deadline:
        time.sleep(0.1)
        remaining = _pids_carrying(token)
    return remaining


@pytest.fixture
def reap_markers() -> Iterator[list[str]]:
    """Kill anything a failing test leaves behind, by exact pid, and say so.

    A test for a leak must not become one: this host runs two dozen sessions, and
    an orphaned sleeper from a red test would outlive it. Killed by PID, and only
    for the token this test planted — never by a program name.
    """
    tokens: list[str] = []
    try:
        yield tokens
    finally:
        for token in tokens:
            for pid in _pids_carrying(token):
                try:
                    os.kill(pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass


#: A pnpm stand-in: it records what it was asked to do, answers ``--version``
#: with the version ``config.json`` names, and — when configured to — plants a
#: grandchild carrying the test's token before lingering like a real build does.
#: Forking is the point: the defect is what happens to a step's DESCENDANTS when
#: the bound fires, and a stand-in that only slept would not have any. The
#: grandchild ignores SIGTERM, so only a SIGKILL rung can clear it.
_FAKE_RUNNER = '''#!/usr/bin/env python3
"""Generated by tests/unit/mobile/test_bundle_build_bound.py — see that module."""

import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONFIG = json.loads((HERE / "config.json").read_text(encoding="utf-8"))
GRANDCHILD = "import signal, time; signal.signal(signal.SIGTERM, signal.SIG_IGN); time.sleep(600)"

#: The instrument: one line per invocation, so a test can assert what the
#: builder did NOT run as well as what it did.
with (HERE / "invocations.jsonl").open("a", encoding="utf-8") as handle:
    handle.write(
        json.dumps(
            {
                "argv": sys.argv[1:],
                "cwd": os.getcwd(),
                "manifest": (Path(os.getcwd()) / "package.json").exists(),
            }
        )
        + "\\n"
    )

if CONFIG.get("deaf"):
    signal.signal(signal.SIGTERM, signal.SIG_IGN)

if "--version" in sys.argv[1:]:
    print(CONFIG["version"])
    raise SystemExit(0)

if CONFIG.get("dist"):
    dist = Path(os.getcwd()) / "dist"
    dist.mkdir(exist_ok=True)
    (dist / "index.html").write_text("<html></html>", encoding="utf-8")

if CONFIG.get("fork"):
    subprocess.Popen(
        [sys.executable, "-c", GRANDCHILD, CONFIG["token"]],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    time.sleep(CONFIG.get("linger", 600))

raise SystemExit(CONFIG.get("exit", 1))
'''


class StandIn:
    """A generated pnpm stand-in inside a temp dir, plus its recorded calls."""

    def __init__(self, root: Path, **config: object) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)
        self.script = root / "stand-in-pnpm"
        self.script.write_text(_FAKE_RUNNER, encoding="utf-8")
        (root / "config.json").write_text(json.dumps(config), encoding="utf-8")

    @property
    def runner(self) -> list[str]:
        """The argv prefix the builder is asked to run.

        Through ``sys.executable`` rather than a shebang: the stand-in must run
        under the interpreter already under test, not under whichever ``python3``
        a PATH lookup finds on this host.
        """
        return [sys.executable, str(self.script)]

    def invocations(self) -> list[dict[str, object]]:
        log = self.root / "invocations.jsonl"
        if not log.exists():
            return []
        return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines()]

    def argv_seen(self) -> list[list[str]]:
        return [list(entry["argv"]) for entry in self.invocations()]  # type: ignore[arg-type]


def _web(tmp_path: Path, *, pin: str | None) -> Path:
    """A build tree: a manifest, and whatever ``packageManager`` pin it carries."""
    web = tmp_path / "web"
    web.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, object] = {"name": "web", "private": True}
    if pin is not None:
        manifest["packageManager"] = pin
    (web / "package.json").write_text(json.dumps(manifest), encoding="utf-8")
    return web


def test_the_bound_reaps_the_group_not_just_the_leader(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, reap_markers: list[str]
) -> None:
    """The field defect: the bound fires, the leader dies, the work does not.

    On the pre-fix tree this test fails with the planted grandchild STILL ALIVE
    after ``_build_bundle`` returned — ``subprocess.run(timeout=...)`` kills the
    direct child only, and nothing else was watching the group.
    """
    token = _token()
    reap_markers.append(token)
    fake = StandIn(tmp_path / "bin", version="11.22.0", fork=True, token=token, linger=600)
    web = _web(tmp_path, pin=None)
    monkeypatch.setattr(install, "_BUILD_STEP_TIMEOUT", 3.0)
    monkeypatch.setattr(install, "_BUILD_KILL_GRACE", 1.0)

    error = install._build_bundle(web, fake.runner)

    assert error is not None, "a step killed by the bound must not read as success"
    assert "bundle build failed" in error
    survivors = _wait_until_gone(token)
    assert survivors == [], (
        f"a descendant of the bounded step survived it ({survivors}): the bound "
        "reached the leader and nothing reached the group"
    )


def test_the_bound_clears_a_group_that_ignores_sigterm(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, reap_markers: list[str]
) -> None:
    """SIGTERM is rung one; a group that ignores it must still be cleared.

    Both processes ignore SIGTERM here, so this holds only if the bound escalates
    to SIGKILL — the grace window is the one thing a bare ``timeout`` waits out.
    """
    token = _token()
    reap_markers.append(token)
    fake = StandIn(
        tmp_path / "bin", version="11.22.0", fork=True, token=token, linger=600, deaf=True
    )
    web = _web(tmp_path, pin=None)
    monkeypatch.setattr(install, "_BUILD_STEP_TIMEOUT", 3.0)
    monkeypatch.setattr(install, "_BUILD_KILL_GRACE", 1.0)

    error = install._build_bundle(web, fake.runner)

    assert error is not None
    survivors = _wait_until_gone(token)
    assert survivors == [], f"a SIGTERM-deaf group ({survivors}) outlived the bound"


def test_a_descendant_does_not_outlive_a_step_that_exits_by_itself(
    tmp_path: Path, reap_markers: list[str]
) -> None:
    """An ordinary exit is not a bound at all, and nothing else reaps the group.

    This is the half ``timeout(1)`` — and a plain ``subprocess.run`` — cannot
    cover by construction: by the time the leader has exited there is nothing
    left to signal, and whatever it forked keeps the machine's memory. This step
    SUCCEEDS, so the assertion is about a green build rather than a killed one,
    and it is the branch the fork bomb regrew on.
    """
    token = _token()
    reap_markers.append(token)
    fake = StandIn(
        tmp_path / "bin", version="11.22.0", fork=True, token=token, linger=0, exit=0, dist=True
    )
    web = _web(tmp_path, pin=None)

    error = install._build_bundle(web, fake.runner)

    assert error is None, f"the stand-in's steps succeed, so this should build: {error}"
    assert (web / "dist" / "index.html").exists()
    survivors = _wait_until_gone(token)
    assert survivors == [], (
        f"a descendant ({survivors}) outlived a step that exited on its own — the "
        "case the sweep exists for, and the one that let the fork bomb regrow "
        "after the first kill"
    )


def test_a_pnpm_that_is_not_the_pinned_one_is_refused_before_anything_runs(
    tmp_path: Path,
) -> None:
    """The recursion's engine, refused: no build step is ever started.

    ``package.json`` pins pnpm@11.22.0 and the runner reports 10.30.3. Asserted on
    the refusal AND on the absence of any ``install``/``build`` invocation,
    because a refusal that still spawned pnpm would leave the engine running.
    """
    fake = StandIn(tmp_path / "bin", version="10.30.3")
    web = _web(tmp_path, pin="pnpm@11.22.0")

    error = install._build_bundle(web, fake.runner)

    assert error is not None
    assert "10.30.3" in error, f"the refusal must name the version on PATH: {error}"
    assert "11.22.0" in error, f"the refusal must name the pinned version: {error}"
    assert "npm install -g pnpm@11.22.0" in error
    assert "corepack enable" in error
    assert "fans out" in error, "the why has to be in the sentence, not only in the code"
    assert fake.argv_seen() == [
        ["--version"]
    ], f"only the version probe may run: {fake.argv_seen()}"


def test_the_version_probe_runs_outside_the_pinned_tree(tmp_path: Path) -> None:
    """WHERE the probe runs is load-bearing, not tidy.

    pnpm reads the nearest ``package.json`` above its cwd, so probing
    ``pnpm --version`` INSIDE the pinned tree does not answer — it starts
    resolving the pin, which is the recursion this guard exists to refuse
    (measured: past 120 s and spawning ``pnpm add pnpm@11.22.0`` children, where
    the same command in an empty directory answered in under a second). Asserted
    on the probe's own recorded cwd.
    """
    fake = StandIn(tmp_path / "bin", version="10.30.3")
    web = _web(tmp_path, pin="pnpm@11.22.0")

    install._build_bundle(web, fake.runner)

    probe = fake.invocations()[0]
    assert (
        probe["manifest"] is False
    ), f"the probe ran in a tree that carries a manifest: {probe['cwd']}"
    assert Path(str(probe["cwd"])) != web


def test_a_matching_pin_builds(tmp_path: Path) -> None:
    """The normal path still works: the guard is a wall, not a wall for everyone.

    What this does NOT show: a real pnpm build. It shows the decision function and
    the wiring — the runner is asked for its version, is allowed through, and both
    steps then run in the pinned tree. The PR says so plainly.
    """
    fake = StandIn(tmp_path / "bin", version="11.22.0", exit=0, dist=True)
    web = _web(tmp_path, pin="pnpm@11.22.0")

    error = install._build_bundle(web, fake.runner)

    assert error is None
    assert fake.argv_seen() == [["--version"], ["install", "--frozen-lockfile"], ["build"]]
    steps = fake.invocations()[1:]
    assert all(
        entry["manifest"] is True for entry in steps
    ), "the build steps must run in the PINNED tree, not in the probe's temp dir"
    assert all(Path(str(entry["cwd"])) == web for entry in steps)


def test_an_unreadable_runner_is_not_refused(tmp_path: Path) -> None:
    """An inconclusive probe proceeds: the GROUP BOUND is the wall.

    Refusing here would trade a rare hang for a common false refusal on machines
    whose pnpm is fine, and the bound already makes a bad build survivable.
    """
    fake = StandIn(tmp_path / "bin", version="", exit=0, dist=True)
    web = _web(tmp_path, pin="pnpm@11.22.0")

    error = install._build_bundle(web, fake.runner)

    assert error is None
    assert ["install", "--frozen-lockfile"] in fake.argv_seen()


def test_corepack_is_the_route_out_and_is_not_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Corepack RESOLVES the pin, so it is never the mismatch this guard refuses.

    Checked on both spellings Corepack reaches us as: the argv
    :func:`install._package_runner` builds, and a ``pnpm`` shim Corepack itself
    installed on PATH — the route the refusal recommends must not be caught by it.
    """
    assert install._corepack_shaped(["corepack", "pnpm"]) is True

    shim = tmp_path / "pnpm"
    shim.write_text('#!/bin/sh\n# corepack shim\nexec corepack pnpm "$@"\n', encoding="utf-8")
    shim.chmod(0o755)
    monkeypatch.setenv("PATH", str(tmp_path))

    assert install._corepack_shaped(["pnpm"]) is True


def test_a_plain_runner_is_not_taken_for_corepack(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The other half of the check: a global pnpm must still be compared to the pin."""
    shim = tmp_path / "pnpm"
    shim.write_text('#!/bin/sh\nexec node /somewhere/pnpm.cjs "$@"\n', encoding="utf-8")
    shim.chmod(0o755)
    monkeypatch.setenv("PATH", str(tmp_path))

    assert install._corepack_shaped(["pnpm"]) is False


@pytest.mark.parametrize(
    ("pin", "expected"),
    [
        ("pnpm@11.22.0", "11.22.0"),
        ("pnpm@11.22.0+sha512.deadbeef", "11.22.0"),
        ("npm@10.9.0", None),
        (None, None),
    ],
)
def test_the_pin_is_read_from_the_trees_own_manifest(
    tmp_path: Path, pin: str | None, expected: str | None
) -> None:
    """Only a pnpm pin is enforceable, and a Corepack integrity suffix is not a version."""
    web = _web(tmp_path, pin=pin)

    assert install._pinned_pnpm(web) == expected


def test_a_tree_with_no_manifest_has_no_pin_to_enforce(tmp_path: Path) -> None:
    """Older snapshots carry no manifest; refusing there would break the updater."""
    empty = tmp_path / "no-manifest"
    empty.mkdir()

    assert install._pinned_pnpm(empty) is None
