// GENERATED by python -m local_operator.browser_bridge.gen_ts. Do not edit.
export const PROTO_VERSION = 1 as const;
// The extension version this runtime was developed and released alongside.
// ADVISORY ONLY: nothing is refused for being older (`MIN_SUPPORTED_PROTO` is
// the compatibility floor). Generated so the popup's update line and the
// daemon's agree by construction.
export const EXPECTED_EXTENSION_VERSION = '0.1.18' as const;
// The ONE spelling of the "a newer extension exists" advisory. `{have}` and
// `{want}` are the reported and the expected extension versions; the
// contingency is on the Chrome Web Store because nothing here can know what the
// store currently offers. Nothing is blocked by an older extension — the copy
// says so, and must keep saying so.
export const EXTENSION_UPDATE_NOTE = 'Browser extension {have} < {want} — update it in Chrome when a newer version is offered; nothing is blocked.';
// How long the approval popup waits for a human origin decision before
// auto-denying. Generated so the daemon's prompt window (this + margin) and
// the session client's HTTP timeout can never drift below it (finding A3).
export const ORIGIN_PROMPT_TIMEOUT_MS = 60000 as const;

export enum ErrorCode {
  EXTENSION_DISCONNECTED = 'extension_disconnected',
  NOT_PAIRED = 'not_paired',
  TAB_CLOSED = 'tab_closed',
  NAV_FAILED = 'nav_failed',
  NAV_TIMEOUT = 'nav_timeout',
  ELEMENT_NOT_FOUND = 'element_not_found',
  ORIGIN_DENIED = 'origin_denied',
  ORIGIN_PROMPT_PENDING = 'origin_prompt_pending',
  ORIGIN_NOT_ALLOWED = 'origin_not_allowed',
  DEBUGGER_CONFLICT = 'debugger_conflict',
  ACCESS_QUEUE_FULL = 'access_queue_full',
  TAB_LIMIT = 'tab_limit',
  TAB_AMBIGUOUS = 'tab_ambiguous',
  BUSY = 'busy',
  PROTO_MISMATCH = 'proto_mismatch',
  OWNER_REFUSED = 'owner_refused',
  EXTENSION_UNRESPONSIVE = 'extension_unresponsive',
  CAPABILITY_UNSUPPORTED = 'capability_unsupported',
  INTERNAL = 'internal',
}

export type Method = 'open' | 'goto' | 'read' | 'snapshot' | 'screenshot' | 'click' | 'type' | 'close' | 'status' | 'tabs' | 'scroll' | 'logs' | 'request_access' | 'await_access' | 'cancel_access' | 'retitle' | 'owner_recover' | 'owner_finish' | 'owner_retain' | 'owner_release' | 'download' | 'upload';
// One buffered console/runtime log line, as `logs` returns it (newest last).
// `level` is normalized to the error/warning/info/log vocabulary the tool
// filters on; `source` distinguishes a page console call from an uncaught
// exception ('console' | 'exception' | 'log-entry').
export interface LogEntry {
  level: string; text: string; source: string; url: string; line: number; timestamp: number;
}
// What `scroll` reports back so the agent knows where the viewport landed and
// whether more content remains past it (so it can stop paging at the end).
export interface ScrollResult {
  scrollX: number; scrollY: number; moreBelow: boolean; moreRight: boolean;
  url: string; title: string;
}
// One file's facts, in the ONE shape both hosts return for `download` and
// `upload` (design §6.1). `sha256` is computed by PYTHON, never by a host: a
// host that reports a hash it did not compute is a host whose word is being
// trusted, which is the property the post-hoc verification exists to remove.
// `sniffed` is what the reporting side observed about the CONTENT ('' when it
// could observe nothing), and `mime` is what the SERVER declared ('' unknown).
export interface FileFact {
  name: string; path: string; bytes: number; mime: string; sniffed: string; sha256: string;
}
// `download` -> the files that landed, whether a capture was armed at all, and
// why not. `armed: false` with a `reason` is a POLICY ANSWER, not a fault: a
// refusal is a result because an already-released daemon drops a frame carrying
// an ErrorCode it does not know (design §6.2).
export interface DownloadResult {
  files: FileFact[]; armed: boolean; reason: string;
}
// `upload` -> the selectors/inputs that accepted files, and the facts of what
// the DOM actually holds after the attach (read back, never assumed).
export interface UploadResult {
  inputs: string[]; accepted: FileFact[];
}
export interface Request { id: string; method: Method; params: Record<string, unknown>; }
export interface ErrorDetail { code: ErrorCode; message: string; data: Record<string, unknown>; }
export type Response =
  | { id: string; ok: true; result: Record<string, unknown> }
  | { id: string; ok: false; error: ErrorDetail };
export interface Hello {
  event: 'hello'; proto: number; token: string; extension_version: string; browser: string;
}
export interface HelloAck {
  event: 'hello_ack'; proto: number; paired: boolean;
  // ADDITIVE: a daemon released before multi-identity simply does not send
  // these, so an absent `role` MUST be read as 'driver' (behave exactly as
  // before). `authorized_count` defaults to 1 for the same reason. Nothing is
  // added to `Hello` instead: the daemon validates it with extra="forbid", so
  // a new field THERE would be closed 4001 by every already-released daemon.
  role?: 'driver' | 'standby';
  authorized_count?: number;
}
// Daemon -> extension: this link's role CHANGED while it stayed connected
// (a failover, or `lop browser drive`). A separate EVENT rather than a field on
// an existing model, so a released daemon that does not know it ignores the
// frame instead of closing the socket.
export interface Role { event: 'role'; role: 'driver' | 'standby'; }
export interface PairRequest { event: 'pair'; code: string; }
export interface PairResult { event: 'pair_result'; ok: boolean; token: string; message: string; }
export interface Ping { event: 'ping'; }
export interface Pong { event: 'pong'; }
// Which wire methods THIS build serves, sent right after hello. An old daemon
// drops the unknown event harmlessly, which is why capability may travel here
// and may not travel as a new field on Hello (extra="forbid" would close the
// socket with 4001). `methods` is the extension's own dispatch table, so an
// advertised capability cannot drift from a served one.
export interface Capabilities {
  event: 'capabilities'; methods: string[]; version: string;
}
export interface TabClosed { event: 'tab_closed'; tab: string; }
export interface TabUpdate { event: 'tab_update'; tab: string; url: string; title: string; }
export interface AwaitingOrigin { event: 'awaiting_origin'; id: string; origin: string; }
export interface AwaitingOriginCleared { event: 'awaiting_origin_cleared'; id: string; }
export interface Unpair { event: 'unpair'; }
export interface OriginDecision {
  event: 'origin_decision'; origin: string; decision: 'once' | 'site' | 'domain' | 'deny';
}
export type ExtensionEvent =
  | Hello | PairRequest | Pong | TabClosed | TabUpdate | AwaitingOrigin | AwaitingOriginCleared
  | Unpair | OriginDecision | Capabilities;
export type DaemonMessage = HelloAck | PairResult | Ping | Request | Role;
