// GENERATED by python -m local_operator.browser_bridge.gen_ts. Do not edit.
export const PROTO_VERSION = 1 as const;
// How long the approval popup waits for a human origin decision before
// auto-denying. Generated so the daemon's prompt window (this + margin) and
// the session client's HTTP timeout can never drift below it (finding A3).
export const ORIGIN_PROMPT_TIMEOUT_MS = 60000 as const;

export enum ErrorCode {
  EXTENSION_DISCONNECTED = 'extension_disconnected',
  NOT_PAIRED = 'not_paired',
  TAB_CLOSED = 'tab_closed',
  NAV_FAILED = 'nav_failed',
  NAV_TIMEOUT = 'nav_timeout',
  ELEMENT_NOT_FOUND = 'element_not_found',
  ORIGIN_DENIED = 'origin_denied',
  ORIGIN_PROMPT_PENDING = 'origin_prompt_pending',
  ORIGIN_NOT_ALLOWED = 'origin_not_allowed',
  DEBUGGER_CONFLICT = 'debugger_conflict',
  ACCESS_QUEUE_FULL = 'access_queue_full',
  TAB_LIMIT = 'tab_limit',
  TAB_AMBIGUOUS = 'tab_ambiguous',
  BUSY = 'busy',
  PROTO_MISMATCH = 'proto_mismatch',
  INTERNAL = 'internal',
}

export type Method = 'open' | 'goto' | 'read' | 'snapshot' | 'screenshot' | 'click' | 'type' | 'close' | 'status' | 'tabs' | 'scroll' | 'logs' | 'request_access' | 'await_access' | 'cancel_access' | 'retitle';
// One buffered console/runtime log line, as `logs` returns it (newest last).
// `level` is normalized to the error/warning/info/log vocabulary the tool
// filters on; `source` distinguishes a page console call from an uncaught
// exception ('console' | 'exception' | 'log-entry').
export interface LogEntry {
  level: string; text: string; source: string; url: string; line: number; timestamp: number;
}
// What `scroll` reports back so the agent knows where the viewport landed and
// whether more content remains past it (so it can stop paging at the end).
export interface ScrollResult {
  scrollX: number; scrollY: number; moreBelow: boolean; moreRight: boolean;
  url: string; title: string;
}
export interface Request { id: string; method: Method; params: Record<string, unknown>; }
export interface ErrorDetail { code: ErrorCode; message: string; data: Record<string, unknown>; }
export type Response =
  | { id: string; ok: true; result: Record<string, unknown> }
  | { id: string; ok: false; error: ErrorDetail };
export interface Hello {
  event: 'hello'; proto: number; token: string; extension_version: string; browser: string;
}
export interface HelloAck { event: 'hello_ack'; proto: number; paired: boolean; }
export interface PairRequest { event: 'pair'; code: string; }
export interface PairResult { event: 'pair_result'; ok: boolean; token: string; message: string; }
export interface Ping { event: 'ping'; }
export interface Pong { event: 'pong'; }
export interface TabClosed { event: 'tab_closed'; tab: string; }
export interface TabUpdate { event: 'tab_update'; tab: string; url: string; title: string; }
export interface AwaitingOrigin { event: 'awaiting_origin'; id: string; origin: string; }
export interface AwaitingOriginCleared { event: 'awaiting_origin_cleared'; id: string; }
export interface Unpair { event: 'unpair'; }
export interface OriginDecision {
  event: 'origin_decision'; origin: string; decision: 'once' | 'site' | 'domain' | 'deny';
}
export type ExtensionEvent =
  | Hello | PairRequest | Pong | TabClosed | TabUpdate | AwaitingOrigin | AwaitingOriginCleared
  | Unpair | OriginDecision;
export type DaemonMessage = HelloAck | PairResult | Ping | Request;
