"""Generate the extension's TypeScript wire declarations.

Usage::

    python -m local_operator.browser_bridge.gen_ts
    python -m local_operator.browser_bridge.gen_ts --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from local_operator.browser_bridge.protocol import PROTO_VERSION, ErrorCode

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET = REPO_ROOT / "extension" / "src" / "protocol.gen.ts"


def render() -> str:
    error_values = "\n".join(f"  {item.name} = {item.value!r}," for item in ErrorCode)
    methods = " | ".join(
        repr(item)
        for item in (
            "open",
            "goto",
            "read",
            "snapshot",
            "screenshot",
            "click",
            "type",
            "close",
            "status",
        )
    )
    return f"""// GENERATED by python -m local_operator.browser_bridge.gen_ts. Do not edit.
export const PROTO_VERSION = {PROTO_VERSION} as const;

export enum ErrorCode {{
{error_values}
}}

export type Method = {methods};
export interface Request {{ id: string; method: Method; params: Record<string, unknown>; }}
export interface ErrorDetail {{ code: ErrorCode; message: string; data: Record<string, unknown>; }}
export type Response =
  | {{ id: string; ok: true; result: Record<string, unknown> }}
  | {{ id: string; ok: false; error: ErrorDetail }};
export interface Hello {{
  event: 'hello'; proto: number; token: string; extension_version: string; browser: string;
}}
export interface HelloAck {{ event: 'hello_ack'; proto: number; paired: boolean; }}
export interface PairRequest {{ event: 'pair'; code: string; }}
export interface PairResult {{ event: 'pair_result'; ok: boolean; token: string; message: string; }}
export interface Ping {{ event: 'ping'; }}
export interface Pong {{ event: 'pong'; }}
export interface TabClosed {{ event: 'tab_closed'; tab: string; }}
export interface TabUpdate {{ event: 'tab_update'; url: string; title: string; }}
export interface AwaitingOrigin {{ event: 'awaiting_origin'; id: string; origin: string; }}
export interface Unpair {{ event: 'unpair'; }}
export interface OriginDecision {{
  event: 'origin_decision'; origin: string; decision: 'once' | 'always' | 'deny';
}}
export type ExtensionEvent =
  | Hello | PairRequest | Pong | TabClosed | TabUpdate | AwaitingOrigin | Unpair | OriginDecision;
export type DaemonMessage = HelloAck | PairResult | Ping | Request;
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    generated = render()
    if args.check:
        try:
            current = TARGET.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != generated:
            print(
                f"{TARGET} is stale; run python -m local_operator.browser_bridge.gen_ts",
                file=sys.stderr,
            )
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(TARGET)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
