"""Versioned messages shared by the browser bridge and Chromium extension.

This module is the protocol's only hand-written source.  The checked-in
TypeScript representation is generated by :mod:`.gen_ts`; keeping the wire
shape here makes a Python-only protocol edit fail CI instead of drifting until
an extension command mysteriously times out.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

PROTO_VERSION = 1


class ErrorCode(StrEnum):
    EXTENSION_DISCONNECTED = "extension_disconnected"
    NOT_PAIRED = "not_paired"
    TAB_CLOSED = "tab_closed"
    NAV_FAILED = "nav_failed"
    NAV_TIMEOUT = "nav_timeout"
    ELEMENT_NOT_FOUND = "element_not_found"
    ORIGIN_DENIED = "origin_denied"
    ORIGIN_PROMPT_PENDING = "origin_prompt_pending"
    DEBUGGER_CONFLICT = "debugger_conflict"
    BUSY = "busy"
    PROTO_MISMATCH = "proto_mismatch"
    INTERNAL = "internal"


class WireModel(BaseModel):
    """Strict envelopes make version skew fail at the boundary, not later."""

    model_config = ConfigDict(extra="forbid")


class Request(WireModel):
    id: str = Field(min_length=1)
    method: str = Field(min_length=1)
    params: dict[str, Any] = Field(default_factory=dict)


class ErrorDetail(WireModel):
    code: ErrorCode
    message: str
    data: dict[str, Any] = Field(default_factory=dict)


class Response(WireModel):
    id: str
    ok: bool
    result: dict[str, Any] | None = None
    error: ErrorDetail | None = None


class Hello(WireModel):
    event: Literal["hello"] = "hello"
    proto: int
    token: str = ""
    extension_version: str
    browser: str


class HelloAck(WireModel):
    event: Literal["hello_ack"] = "hello_ack"
    proto: int = PROTO_VERSION
    paired: bool


class PairRequest(WireModel):
    event: Literal["pair"] = "pair"
    code: str = Field(pattern=r"^[0-9]{6}$")


class PairResult(WireModel):
    event: Literal["pair_result"] = "pair_result"
    ok: bool
    token: str = ""
    message: str = ""


class Ping(WireModel):
    event: Literal["ping"] = "ping"


class Pong(WireModel):
    event: Literal["pong"] = "pong"


class TabClosed(WireModel):
    event: Literal["tab_closed"] = "tab_closed"
    tab: str


class TabUpdate(WireModel):
    """Extension -> daemon: the driven tab navigated. Lets the daemon report the
    current page to the Connected popup without an extra RPC (finding U3)."""

    event: Literal["tab_update"] = "tab_update"
    url: str = ""
    title: str = ""


class AwaitingOrigin(WireModel):
    """Extension -> daemon: a command is blocked on a human origin decision, so
    the daemon extends that command's deadline past the base timeout (A3) and
    can surface the pending site (U2)."""

    event: Literal["awaiting_origin"] = "awaiting_origin"
    id: str
    origin: str = ""


class Unpair(WireModel):
    """Extension -> daemon: the options page revoked pairing, so the daemon must
    drop the live socket, not merely the next reconnect (findings A5/U1)."""

    event: Literal["unpair"] = "unpair"


class OriginDecision(WireModel):
    event: Literal["origin_decision"] = "origin_decision"
    origin: str
    decision: Literal["once", "always", "deny"]
