"""Versioned messages shared by the browser bridge and Chromium extension.

This module is the protocol's only hand-written source.  The checked-in
TypeScript representation is generated by :mod:`.gen_ts`; keeping the wire
shape here makes a Python-only protocol edit fail CI instead of drifting until
an extension command mysteriously times out.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

PROTO_VERSION = 1

#: The oldest protocol version this daemon still drives.
#:
#: ``PROTO_VERSION`` and ``MIN_SUPPORTED_PROTO`` are a WINDOW, not an equality,
#: because the two release lines move at different speeds and the extension's
#: half can be stuck in Chrome Web Store review for days (the 0.1.8 review took
#: ~4.5 days). An equality test means a daemon release strands every installed
#: browser until Google approves the matching extension, and the failure the
#: user sees tells them to update an extension the store will not serve yet.
#: That is not hypothetical: it is the defect this window removes.
#:
#: Raising this floor is a real compatibility decision, not a version bump. The
#: rule is stated in docs/design/browser-extension.md section 11 and repeated
#: here because it is the thing most likely to be violated by accident, in BOTH
#: directions:
#:
#: * ``MIN_SUPPORTED_PROTO`` may be raised ONLY by a commit that changes the
#:   meaning of an existing frame shape or an existing method's semantics, and
#:   that commit must state, for the proto it drops, that a peer at that proto
#:   either behaves correctly or receives a typed refusal on exactly the affected
#:   commands — never a silently wrong answer.
#: * …and such a commit MUST raise it (and bump ``PROTO_VERSION``, which is the
#:   same act from the other side) in that same commit. Stated as a permission
#:   alone, a future bumper can follow the rule verbatim, leave the floor at the
#:   proto it just broke, and reach the silently-wrong-answer case the rule
#:   forbids — by obeying the rule. Additive optional fields, new
#:   ``ErrorCode``s the peer only emits, and new events an old peer harmlessly
#:   drops are what keep the floor where it is.
MIN_SUPPORTED_PROTO = 1


def proto_supported(
    proto: int, *, low: int = MIN_SUPPORTED_PROTO, high: int = PROTO_VERSION
) -> bool:
    """Whether ``proto`` falls inside the supported window, inclusive.

    The bounds are parameters rather than a closed-over pair so the acceptance
    rule can be asserted on a SYNTHETIC window: at today's width
    (``MIN_SUPPORTED_PROTO == PROTO_VERSION == 1``) the window and an equality
    test accept exactly the same set, so nothing behavioural can distinguish
    them, and a future revert to ``!=`` would pass every handshake test that
    only ever sends proto 1 (review R1-6). Callers that want the live window
    pass the constants explicitly; ``daemon.py`` does, so monkeypatching the
    module's own names still moves the bound.
    """
    return low <= proto <= high


#: The extension version this runtime was developed and released alongside.
#:
#: Hand-written rather than generated, and pinned to ``extension/manifest.json``
#: by a unit test, so a drift between the two fails CI instead of surfacing as a
#: mystery skew at a user's desk. It is ADVISORY ONLY: nothing is refused for
#: being older, and nothing is forced by it. Its one use is the update advisory
#: below, which says a newer version exists without claiming the build is
#: unusable — the store decides when a newer version is actually offered.
#:
#: 0.1.19 is the first tree whose file-transfer capabilities are OPT-IN: it
#: serves `upload` and `download`, each behind its own switch in the extension's
#: options page, and `download` behind the optional `downloads` permission the
#: operator grants when they turn that switch on (design §17.13). 0.1.18
#: advertised capabilities and served `upload` unconditionally.
EXPECTED_EXTENSION_VERSION = "0.1.19"

#: The first extension version that serves each capability-gated method.
#:
#: Capability travels in the `Capabilities` event and the host records, never in
#: version arithmetic (design §6.3) — this table exists only for the REFUSAL
#: copy, where "this host predates the feature, update it" and "this host is
#: current but stopped answering" need opposite remedies and only the version
#: separates them. The same distinction `OWNERSHIP_MIN_EXTENSION_VERSION` draws.
#:
#: `download` has a floor of 0.1.19 rather than 0.1.18 because no earlier tree
#: could serve it at all: E1x in `docs/design/browser-file-transfer.md` measured
#: that Chrome refuses a tab-scoped `chrome.debugger` session the only two CDP
#: primitives that could put a file where the harness chooses (Chrome 153.0.8010.53:
#: `-32000 "Cannot not access browser-level commands"` and `-32601`). The tree
#: that CAN serve it does so through `chrome.downloads`, which needs the optional
#: permission — so an older build here is a build to UPDATE, and the copy says so
#: instead of the retired "no extension build can" sentence.
CAPABILITY_MIN_EXTENSION_VERSION: dict[str, str] = {"upload": "0.1.18", "download": "0.1.19"}

#: The two switches the OPERATOR owns, and the ONE spelling of each label.
#:
#: These capabilities are OFF by default and only the operator may turn them on:
#: the options page writes the flag on a human gesture, and no daemon frame, tool
#: call or page can reach it (design §17.13). The label is here rather than in the
#: refusal copy because it names a control the user has to find in a UI this
#: process cannot see, and the same string has to appear in Python's refusal, the
#: extension's refusal and the options page — three writers, one spelling, and
#: the generated table is what keeps them equal (`gen_ts.py`).
CAPABILITY_SWITCH_LABEL: dict[str, str] = {
    "download": "Allow downloads",
    "upload": "Allow uploads",
}

#: The Chrome permission a switch needs, when it needs one.
#:
#: Only `download` needs a permission, and it is REQUESTED at the moment the
#: operator turns the switch on rather than declared at install time — an update
#: must never widen what an installed extension can do without the user asking
#: for it. `upload` needs none: it rides the `debugger` permission the extension
#: already holds.
CAPABILITY_SWITCH_PERMISSION: dict[str, str] = {"download": "downloads"}

#: Where the switches live, in the ONE spelling every refusal uses.
#:
#: A refusal that names a switch but not where to find it leaves the user
#: hunting; naming a URL we cannot know (the extension id differs between an
#: unpacked and a store install) would be worse, so the copy names the two
#: Chrome surfaces that lead there for any install.
CAPABILITY_SWITCH_LOCATION = (
    "the Local Operator extension's options page "
    "(chrome://extensions -> Details -> Extension options)"
)

#: The methods a host must ADVERTISE before the daemon will send them.
#:
#: Every method that predates the capability advertisement is deliberately absent:
#: refusing those on a pre-feature peer would break a host that works today. This
#: set is therefore exactly "the methods whose absence a peer cannot report as
#: anything better than a bare `internal`" — which is what the refusal exists for.
CAPABILITY_GATED_METHODS: frozenset[str] = frozenset({"download", "upload"})

#: The first extension TREE that carried the ``owner_*`` ownership lifecycle
#: (PR #798, ``ee146fb73``), whose manifest reads ``0.1.9`` — verify with
#: ``git show ee146fb73:extension/manifest.json``, and note that the same commit
#: already lists ``owner_recover``/``owner_finish``/``owner_retain``/
#: ``owner_release`` in ``extension/src/protocol.gen.ts``.
#:
#: It is a TREE, not a store release: 0.1.9 was never submitted (the release
#: record says so, and the manifest stopped naming one tree — the reason 0.1.10
#: exists), but it is not a fiction either: an unpacked/sideload build of that
#: tree is a peer this runtime can meet, and the design doc treats that path as
#: supported. So the floor is the first build that SHIPS the lifecycle, and a
#: 0.1.9 peer is ownership-CAPABLE: it must reach the wedge arm, not the silent
#: degradation, because a bare ``internal`` from it means its worker stopped
#: answering — not that it has no verbs. Getting this wrong is not cosmetic:
#: the degraded path is the one place the session stops using ``owner_*``, so
#: misclassifying a capable peer both hides a real wedge and (before R1-2) left
#: its tab unclosable.
#:
#: Used to tell two identical-looking failures apart. ``owner_recover``
#: answering with a bare ``internal`` and empty ``data`` means either "this
#: extension predates ownership" or "this extension is current but its worker
#: stopped answering"; the two need opposite remedies, and only the reported
#: version separates them. Below this floor we degrade to the capability-only
#: path and keep working; at or above it we report a wedge honestly.
OWNERSHIP_MIN_EXTENSION_VERSION = "0.1.9"

#: The ONE spelling of the "a newer extension exists" advisory.
#:
#: Deliberately a template over two version strings, never a sentence with a
#: number baked in, so the daemon, the CLI, the popup and the agent-facing line
#: cannot drift and a version bump cannot leave a stale figure in copy. The
#: contingency is on the STORE ("when a newer version is offered") because
#: Python cannot know the store's live version and must not pretend to — and the
#: register is deliberately not the old "requires"/"must" one: nothing here
#: blocks anything, which is the whole point of the change that introduced it.
EXTENSION_UPDATE_NOTE = (
    "Browser extension {have} < {want} — update it in Chrome when a newer version is "
    "offered; nothing is blocked."
)


def parse_extension_version(value: str) -> tuple[int, ...] | None:
    """Parse a dotted numeric version, or ``None`` when it is not one.

    Chrome version strings are digits and dots (``"0.1.10"``), so anything else
    — an empty string from a peer that never stamped one, a placeholder, a user
    agent — is UNKNOWN rather than "older". Every caller must read ``None`` as
    "cannot tell": an unknown version must not trigger the update advisory and
    must not be treated as a pre-ownership extension, because both would be a
    claim the evidence does not support.
    """
    value = value.strip()
    if not value:
        return None
    parts = value.split(".")
    if any(not part.isdigit() for part in parts):
        return None
    return tuple(int(part) for part in parts)


def extension_older(have: str, want: str) -> bool:
    """Whether ``have`` is a KNOWN version strictly older than ``want``.

    ``False`` whenever either side is unparseable, so "unknown" is never
    silently promoted to "older". Component-wise, and a shorter version is a
    prefix of a longer one rather than an error: ``0.1.9 < 0.1.10`` and
    ``0.1 < 0.1.13``, both of which a string comparison gets wrong.
    """
    parsed_have = parse_extension_version(have)
    parsed_want = parse_extension_version(want)
    if parsed_have is None or parsed_want is None:
        return False
    return parsed_have < parsed_want


def extension_update_note(have: str, want: str = EXPECTED_EXTENSION_VERSION) -> str:
    """The advisory sentence, generated from the constants (never hardcoded)."""
    return EXTENSION_UPDATE_NOTE.format(have=have, want=want)


#: Every RPC method the extension answers, in a stable order. This is the ONE
#: source of truth: the daemon's timeout table, the tool's action list, and the
#: generated TypeScript ``Method`` union all derive from it, so a method added
#: here without a handler fails a test rather than timing out on the wire, and a
#: method the extension can serve but nobody advertises simply does not exist.
#: ``scroll`` and ``logs`` are bridge-only capabilities (cmux degrades with a
#: typed error); they still live here because the wire protocol is shared.
METHODS = (
    "open",
    "goto",
    "read",
    "snapshot",
    "screenshot",
    "click",
    "type",
    "close",
    "status",
    # tabs lists every live extension-owned surface. It exists because parallel
    # sessions now each open their OWN tab (open no longer reuses another
    # session's surface), so agents need read-only discovery of what is being
    # driven. Listed handles are REDACTED (nonce truncated): the full token is
    # the drive capability, granted only by the surface's own `open` response,
    # so the listing is genuinely awareness-only. Bridge-only, like
    # scroll/logs: cmux has no multi-surface registry.
    "tabs",
    "scroll",
    "logs",
    # Site-permission flow (agent-legible approvals). ``request_access`` raises
    # the pending approval in the extension and returns immediately;
    # ``await_access`` blocks for a BOUNDED slice (the extension caps it well
    # under the command timeout) and the tool loops slices client-side. Split
    # this way because the old design — one navigation RPC that silently sat
    # on the 60 s popup prompt — expired unseen (the agent never got a turn to
    # tell the user to look at the popup) and made the session client time out
    # with a misleading "bridge unreachable" (sessions misdiagnosed the bridge
    # as broken and burned an hour on it).
    "request_access",
    "await_access",
    # Requester-bound cancellation removes only this session's exact-origin
    # pending entry; it cannot dismiss another session's consent prompt.
    "cancel_access",
    # Push a session title that arrived AFTER the tab was opened, so the tab
    # group stops wearing the label the session had at open time. A
    # conversation names itself asynchronously a second or two into its first
    # turn, which is usually after the opening "look at this page" already
    # created the group; every other command reconciles the group as a side
    # effect (worker.ts dispatch), but an open -> screenshot -> close session
    # issues no later command and so never self-healed. Presentation only: it
    # drives no tab, reads no page, and returns nothing but the applied label.
    "retitle",
    "owner_recover",
    "owner_finish",
    "owner_retain",
    "owner_release",
    # File transfer, and both halves are gated by the same mechanism — measured,
    # not assumed (design §12.4's E1x, `docs/design/browser-file-transfer.md`):
    #
    # * `upload` is servable on both non-cmux hosts. The extension attaches files
    #   with `DOM.setFileInputFiles` over the tab-scoped session it already holds
    #   (the same primitive Puppeteer/Playwright use), which needs no new
    #   permission.
    # * `download` is served by the desktop app's host, and from extension 0.1.19
    #   by the extension through `chrome.downloads`. The CDP primitives that would
    #   let an extension choose a destination are refused to a tab-scoped session
    #   (§17.1), so the extension's file lands in the user's own download
    #   directory first and the harness relocates it (§17.13, §11.5 R7).
    #
    # Both are listed here regardless: this tuple is the protocol's vocabulary,
    # and the per-host answer to "who serves this" is the `Capabilities` event
    # plus the `CapabilitySwitches` event — never a fork of the vocabulary. On an
    # extension host each method is additionally behind the operator's own switch
    # (protocol.CAPABILITY_SWITCH_LABEL), so a host that CAN serve it may still be
    # answering "not enabled" rather than "not capable".
    "download",
    "upload",
)


#: How long the extension's approval popup gives the user to answer an origin
#: prompt before auto-denying with a typed ORIGIN_DENIED (origins.ts consumes
#: the generated copy in protocol.gen.ts). Milliseconds because it feeds a
#: chrome ``setTimeout`` directly.
#:
#: Timeout-chain invariant (finding A3): extension deny (60 s) < daemon prompt
#: window (65 s) < session client timeout (base command timeout + prompt window
#: + margin, backend.py). Each layer must outlive the one below it so the
#: innermost deadline always wins the race and the session receives a TYPED
#: answer (origin_denied / nav_timeout / result) instead of a transport
#: timeout. When the session client fired first (it used a flat 30–35 s), a
#: healthy daemon waiting on a human was misreported as "bridge unreachable"
#: and a QA session (transcript 0ee4974ba84a) burned an hour restarting a
#: daemon that was fine. All three constants live in or derive from this
#: module so the relationship cannot drift.
ORIGIN_PROMPT_TIMEOUT_MS = 60_000

#: Per-method base budgets for a command the extension is actively serving.
#: The daemon enforces these; the session client derives its own longer
#: HTTP timeout from them (backend.py) so the daemon's typed timeout always
#: arrives before the client gives up.
COMMAND_TIMEOUTS = {
    "owner_recover": 20.0,
    "owner_finish": 20.0,
    "owner_retain": 20.0,
    "owner_release": 20.0,
    "open": 30.0,
    "goto": 30.0,
    "click": 25.0,
    "type": 25.0,
    "read": 20.0,
    "snapshot": 20.0,
    "screenshot": 20.0,
    "close": 20.0,
    "status": 20.0,
    # tabs, like status, names no tab and does no navigation: it enumerates the
    # extension's surface map and prunes dead entries, a handful of chrome.tabs
    # calls. It rides the same global lock key (no ``tab`` param) so a listing
    # cannot interleave with an in-flight open's map write.
    "tabs": 20.0,
    # scroll waits briefly for the wheel/scrollIntoView to settle and re-reads
    # position; logs just drains a per-tab ring buffer already in memory.
    "scroll": 20.0,
    "logs": 20.0,
    # request_access only writes the pending record and raises the prompt
    # surfaces — it returns immediately, never waiting on the human.
    "request_access": 20.0,
    # await_access polls the stored decision for one BOUNDED slice (the
    # extension caps itself at 20 s — access.ts AWAIT_SLICE_MS); the tool
    # loops slices client-side, so this stays an honest per-RPC bound and
    # never needs the awaiting_origin deadline-extension machinery above.
    "await_access": 25.0,
    "cancel_access": 20.0,
    # retitle touches chrome.tabGroups and nothing else — no navigation, no
    # settle, no debugger. It rides the ordinary floor rather than a tighter
    # bound because the group queue it joins is shared and briefly serialises
    # behind an in-flight open's own reconcile.
    "retitle": 20.0,
    # download waits on a PAGE, not on us: the click that starts it may be
    # followed by a slow server, and the agent's own `timeout_s` may raise the
    # wait (clamped to DOWNLOAD_TIMEOUT_MAX_S in browser_files). The daemon's
    # budget is the ceiling, and it is the one method in this table whose bound
    # is measured in minutes rather than seconds — a 200 MB file on a slow link
    # legitimately takes longer than any other action here.
    "download": 120.0,
    # upload is local: the browser reads the bytes off disk, so the budget covers
    # the attach plus the read-back that proves the DOM holds them. A 256 MB
    # attach is the worst case (UPLOAD_MAX_BYTES), not the common one.
    "upload": 60.0,
}

#: Extra budget granted to a command that is BLOCKED on a human origin
#: decision, on top of the base command timeout. The extension gives the user
#: 60 s to answer (ORIGIN_PROMPT_TIMEOUT_MS above); without this the 25–30 s
#: command timeout fired first, so a user who took longer than that got a
#: spurious tool failure while the tab navigated anyway against a surface the
#: session had written off (finding A3). Derived slightly above the extension's
#: deny-timeout so that deny wins the race and returns a typed ORIGIN_DENIED
#: rather than this firing blind.
ORIGIN_PROMPT_WINDOW_S = ORIGIN_PROMPT_TIMEOUT_MS / 1000 + 5.0


class ErrorCode(StrEnum):
    EXTENSION_DISCONNECTED = "extension_disconnected"
    NOT_PAIRED = "not_paired"
    TAB_CLOSED = "tab_closed"
    NAV_FAILED = "nav_failed"
    NAV_TIMEOUT = "nav_timeout"
    ELEMENT_NOT_FOUND = "element_not_found"
    ORIGIN_DENIED = "origin_denied"
    ORIGIN_PROMPT_PENDING = "origin_prompt_pending"
    # A top-level open/goto to an origin the user has not approved. Raised
    # EARLY, before any prompt exists, so the agent can run the explicit
    # request_access -> notify user -> await_access flow instead of blocking a
    # navigation on a popup prompt the user never saw.
    ORIGIN_NOT_ALLOWED = "origin_not_allowed"
    DEBUGGER_CONFLICT = "debugger_conflict"
    # The extension refuses to open more concurrent tabs than its cap (see
    # MAX_SURFACES in extension/src/state.ts): parallel sessions each own a
    # tab now, and without a bound an agent fleet could spray tabs into the
    # user's real browser. Typed so the tool can tell the agent to close one.
    ACCESS_QUEUE_FULL = "access_queue_full"
    TAB_LIMIT = "tab_limit"
    # A bare `close` while several tabs are open: the request is
    # under-specified, not a bridge fault, so it must not render as an
    # "internal" bridge error (review finding n1). The message carries the
    # REDACTED live handles so the caller can pick its own.
    TAB_AMBIGUOUS = "tab_ambiguous"
    BUSY = "busy"
    PROTO_MISMATCH = "proto_mismatch"
    # An ownership-aware refusal: stale generation, foreign proof, ended scope,
    # a tab belonging to another owner. Typed so the session can tell it from a
    # bridge fault WITHOUT substring-matching a human message. That distinction
    # is what makes an `internal` reply to an `owner_*` method mean "this
    # extension predates ownership" — an already-released extension's wording
    # cannot be retrofitted, so the NEW side is what has to be unambiguous.
    OWNER_REFUSED = "owner_refused"
    # The extension socket is TCP-open and paired but has stopped answering:
    # either no frame of ANY kind for LINK_SILENCE_TIMEOUT_S, or a command that
    # consumed its whole budget while the link was already silent. A code of its
    # own rather than a reuse of EXTENSION_DISCONNECTED, whose client copy tells
    # the user to open a browser that is in fact already open — reusing it would
    # re-create, in a new place, exactly the misdiagnosis that made the reported
    # incident expensive. Not BUSY either: BUSY means "retry this action once",
    # and an immediate retry lands on the same poisoned chain.
    #
    # Daemon-to-session only: the extension leg never parses ErrorCode (it only
    # emits one), and an old daemon simply never produces this value, so it
    # needs no PROTO_VERSION bump. Adding a code the EXTENSION could emit would:
    # an old daemon validates `ErrorDetail.code` against this enum, so a value
    # it does not know fails Response.model_validate and the frame is dropped.
    EXTENSION_UNRESPONSIVE = "extension_unresponsive"
    # The attached host cannot serve the requested method, and said so by not
    # advertising it. Daemon-to-session only, and for the SAME reason spelled out
    # above `EXTENSION_UNRESPONSIVE`: an already-released daemon validates
    # `ErrorDetail.code` against this enum, so a deliberate policy refusal must
    # never travel as an error code from the extension — it travels as an
    # `ok: true` result with a reason in the payload (design §6.2), and only the
    # daemon, which is on the safe side of the direction, emits this one.
    #
    # It exists instead of a 120-second timeout: the extension answers an unknown
    # method with a bare `internal` (worker.ts's dispatch), so sending `download`
    # to a host that does not serve it would burn the whole budget and then
    # report an internal error naming nothing actionable. The daemon checks first
    # and answers immediately with this code and the host's own advertised list.
    CAPABILITY_UNSUPPORTED = "capability_unsupported"
    # --- The desktop app's console namespace (design ui-console-tab §10.6) ---
    #
    # The console rides THIS wire and THIS enum rather than a parallel taxonomy,
    # because a second vocabulary for the same class of refusal is how copy
    # drifts. These values are emitted by the APP's RPC host (`local-operator-ui`,
    # PR A of the console split) and parsed by a `lop` session; the daemon never
    # produces them and the extension has no handler for them. Additive in the
    # sense `MIN_SUPPORTED_PROTO`'s rules mean: a peer that does not know a code
    # never emits it, and an OLD session that receives one fails
    # `Response.model_validate` and reports an unreadable answer — which is that
    # peer's version-skew behaviour, not a wire break. No proto bump either way.
    #
    # Names are reused from the existing vocabulary wherever a value fits (the
    # doc's rule); these ten are the ones a reuse would have made a lie:
    #
    # * `unsupported_method` — this app version has no console at all. A TYPED
    #   refusal, so the caller can say "update the app" instead of
    #   substring-matching a message (which is what keeps the floor at 1).
    # * `surface_unavailable` — no such surface on this host, or a stale handle
    #   after a relaunch.
    # * `surface_not_owned` — the surface exists and belongs to ANOTHER session.
    #   The browser's `owner_refused` precedent: typed so a caller does not have
    #   to tell it apart from `surface_unavailable` by reading prose.
    # * `process_exited` — the pty's program is gone; the log is retained and
    #   `console_read` still works.
    # * `input_queue_full` — the app refused more bytes for a surface that is not
    #   draining them, and says how many it took.
    # * `unknown_key` — a named key the encoder does not have; carries the set it
    #   does accept.
    # * `secure_input_active` — read/screenshot refused while the human holds the
    #   secure-input span.
    # * `console_unavailable` — the console feature is off in this app (settings,
    #   env flag, or a pty load failure) and names which of the three it was.
    # * `invalid_grid` — requested cols/rows outside what the app will honour;
    #   carries the clamp it applied.
    # * `console_capture_full` — the app's one-at-a-time offscreen capture view is
    #   already in use (design §13.3). Answered by the app that HAS the capture
    #   view (PR B, §17.1).
    # * `capture_unavailable` — no pane is displaying the surface, so the app has
    #   nothing to photograph. Answered by an app that has no offscreen capture
    #   view yet (PR A, §13.2/§17.1) — the two are DIFFERENT conditions on
    #   different hosts, and modelling only one of them made the ordinary state of
    #   the shipped app read as "your app is newer than this session". The app half
    #   documents this as its one deliberate addition to §10.6
    #   (`local-operator-ui` src/main/console/protocol.ts); this is the session
    #   half of the same contract.
    UNSUPPORTED_METHOD = "unsupported_method"
    SURFACE_UNAVAILABLE = "surface_unavailable"
    SURFACE_NOT_OWNED = "surface_not_owned"
    PROCESS_EXITED = "process_exited"
    INPUT_QUEUE_FULL = "input_queue_full"
    UNKNOWN_KEY = "unknown_key"
    SECURE_INPUT_ACTIVE = "secure_input_active"
    CONSOLE_UNAVAILABLE = "console_unavailable"
    INVALID_GRID = "invalid_grid"
    CONSOLE_CAPTURE_FULL = "console_capture_full"
    CAPTURE_UNAVAILABLE = "capture_unavailable"
    INTERNAL = "internal"


class WireModel(BaseModel):
    """Strict envelopes make version skew fail at the boundary, not later."""

    model_config = ConfigDict(extra="forbid")


class Request(WireModel):
    id: str = Field(min_length=1)
    method: str = Field(min_length=1)
    params: dict[str, Any] = Field(default_factory=dict)


class ErrorDetail(WireModel):
    code: ErrorCode
    message: str
    data: dict[str, Any] = Field(default_factory=dict)


class Response(WireModel):
    id: str
    ok: bool
    result: dict[str, Any] | None = None
    error: ErrorDetail | None = None


class Hello(WireModel):
    event: Literal["hello"] = "hello"
    proto: int
    token: str = ""
    extension_version: str
    browser: str


class HelloAck(WireModel):
    """Daemon -> extension: the handshake verdict.

    ``role`` and ``authorized_count`` are ADDITIVE and always optional at the
    reader: the daemon answers with them, a released daemon never did, and the
    extension must therefore treat an absent ``role`` as "driver", i.e. behave
    exactly as it did before this existed. That is what keeps the compat matrix
    open in BOTH directions without a ``PROTO_VERSION`` bump — a bump would
    close the published store build with 4001, whose popup copy is an unfixable
    "update needed" card (design §7).
    """

    event: Literal["hello_ack"] = "hello_ack"
    proto: int = PROTO_VERSION
    paired: bool
    #: Which side of the pairing this socket is. "standby" means: paired, and
    #: deliberately not sent any Request, because another authorised identity is
    #: driving. The extension detaches its debugger sessions and clears its
    #: surface map on this answer — a standby that kept them would leave the
    #: user with "Local Operator is debugging this browser" banners on tabs
    #: nothing can reach (design §2.3).
    role: Literal["driver", "standby"] = "driver"
    #: How many identities this daemon will accept. Defaults to 1 for the older
    #: daemon that predates the allow-list.
    authorized_count: int = 1


class Role(WireModel):
    """Daemon -> extension: this link's role CHANGED while it was connected.

    Sent on a failover and on an explicit ``lop browser drive``. A new EVENT
    rather than a new field on an existing model, deliberately: the daemon's
    receive loop dispatches on the event name and falls through to
    ``Response.model_validate`` for anything it does not recognise, which raises
    and is ignored — so a released daemon silently ignores this frame instead of
    closing the socket (design §7.1 rule 3). A standby that misses it still
    re-learns its role at its next ``hello``.
    """

    event: Literal["role"] = "role"
    role: Literal["driver", "standby"] = "driver"


class PairRequest(WireModel):
    event: Literal["pair"] = "pair"
    code: str = Field(pattern=r"^[0-9]{6}$")


class PairResult(WireModel):
    event: Literal["pair_result"] = "pair_result"
    ok: bool
    token: str = ""
    message: str = ""


class Ping(WireModel):
    event: Literal["ping"] = "ping"


class Pong(WireModel):
    event: Literal["pong"] = "pong"


class Capabilities(WireModel):
    """Extension -> daemon: which wire methods THIS BUILD serves.

    Sent immediately after ``hello``, and it is how capability travels in this
    protocol rather than through version arithmetic (design §6.3). Two reasons
    it is an EVENT and not a field on ``Hello``: ``Hello`` is validated with
    ``extra="forbid"``, so a new field there would be closed 4001 by every
    already-released daemon — a store build's popup showing an unfixable
    "update needed" card — while an unknown EVENT is harmlessly dropped by an
    old daemon (``protocol.py``'s own rule for what keeps ``PROTO_VERSION``
    where it is). The same shape as ``TabClosed``/``TabUpdate``/``Unpair``.

    ``methods`` is the extension's OWN dispatch table, not a hand-written list,
    so an advertised capability cannot drift from a served one. ``version`` is
    repeated from ``hello`` because the two frames are independent: a daemon
    that missed ``hello``'s version, or a test peer that sends only this frame,
    must not have to infer it.

    Why the daemon must refuse to SEND an unadvertised method rather than let the
    peer fail it: an unknown method gets a bare ``internal`` from the worker
    (``worker.ts``), which spends the whole command budget and then reports
    nothing the caller can act on.
    """

    event: Literal["capabilities"] = "capabilities"
    methods: list[str] = Field(default_factory=list)
    version: str = ""


class CapabilitySwitches(WireModel):
    """Extension -> daemon: which SERVED-ABLE methods the OPERATOR has switched off.

    A SECOND event rather than a field on :class:`Capabilities`, and that is not
    a style choice: every envelope in this module is ``extra="forbid"``
    (:class:`WireModel`), so a new key on an EXISTING event is closed by every
    already-released daemon — the exact failure a new field on ``Hello`` would
    cause, and the reason capability travels as an event at all. A new event is
    dropped harmlessly by an old daemon and read by a new one, which is what lets
    this ship with ``PROTO_VERSION`` still at 1.

    Why the distinction has to reach the harness at all: an empty ``methods``
    list has three causes with three different remedies, and telling them apart is
    the whole point of ``capabilities_known`` and this event. (1) The build cannot
    serve the method — update the extension. (2) The build CAN and the operator
    has not turned its switch on — send them to the switch, because no update
    will change it. (3) The build should serve it and did not — a wedge. Without
    this event (2) is indistinguishable from (3), and the user is sent to toggle
    an extension that is working perfectly.

    ``disabled`` names only methods the ACTIVE BUILD supports; a switch this
    build has no code for must not appear here, because the remedy for it is an
    update, not a toggle. The extension computes it from its own switch table and
    its live permission state, so a switch whose Chrome permission was revoked
    reports as disabled rather than as on.
    """

    event: Literal["capability_switches"] = "capability_switches"
    disabled: list[str] = Field(default_factory=list)
    version: str = ""


class TabClosed(WireModel):
    """Extension -> daemon: one driven tab is gone.

    Emitted from the extension's top-level ``chrome.tabs.onRemoved`` /
    ``onReplaced`` listeners and on an explicit ``close``, so a tab closed by
    the USER clears the daemon's driven record too. Nothing sent this event
    before, which is why ``status`` could advertise a tab that had been closed
    hours earlier. ``tab`` names the surface so one session's close cannot
    blank another session's still-live tab; an empty value means "unknown",
    which the daemon treats as clear-all.
    """

    event: Literal["tab_closed"] = "tab_closed"
    tab: str = ""


class TabUpdate(WireModel):
    """Extension -> daemon: the driven tab navigated. Lets the daemon report the
    current page to the Connected popup without an extra RPC (finding U3).

    ``tab`` is the surface handle: driven pages are tracked PER TAB, because a
    single global slot showed whichever tab was touched last as though it were
    the one bound tab. Defaulted for compatibility with an older extension that
    sent no handle.
    """

    event: Literal["tab_update"] = "tab_update"
    tab: str = ""
    url: str = ""
    title: str = ""


class AwaitingOrigin(WireModel):
    """Extension -> daemon: a command is blocked on a human origin decision, so
    the daemon extends that command's deadline past the base timeout (A3) and
    can surface the pending site (U2)."""

    event: Literal["awaiting_origin"] = "awaiting_origin"
    id: str
    origin: str = ""


class AwaitingOriginCleared(WireModel):
    """Extension -> daemon: a previously announced command is NO LONGER blocked
    on a human origin decision — its queue entry expired, was cancelled, or was
    decided without a response the daemon will see. The daemon pops its record
    so /health stops echoing a prompt the extension no longer shows; without
    this the echo outlived the queue entry and the popup looped on a stale
    request it could never resolve."""

    event: Literal["awaiting_origin_cleared"] = "awaiting_origin_cleared"
    id: str


class Unpair(WireModel):
    """Extension -> daemon: the options page revoked pairing, so the daemon must
    drop the live socket, not merely the next reconnect (findings A5/U1)."""

    event: Literal["unpair"] = "unpair"


class OriginDecision(WireModel):
    event: Literal["origin_decision"] = "origin_decision"
    origin: str
    # "site" is the exact-origin grant (the old "always"), "domain" the
    # registrable-domain or loopback-host grant. The daemon never carries this
    # frame (dropped at daemon.py:730); it is documentation for the wire
    # contract and stays in sync with the extension via protocol.gen.ts.
    decision: Literal["once", "site", "domain", "deny"]
