"""Versioned messages shared by the browser bridge and Chromium extension.

This module is the protocol's only hand-written source.  The checked-in
TypeScript representation is generated by :mod:`.gen_ts`; keeping the wire
shape here makes a Python-only protocol edit fail CI instead of drifting until
an extension command mysteriously times out.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

PROTO_VERSION = 1

#: Every RPC method the extension answers, in a stable order. This is the ONE
#: source of truth: the daemon's timeout table, the tool's action list, and the
#: generated TypeScript ``Method`` union all derive from it, so a method added
#: here without a handler fails a test rather than timing out on the wire, and a
#: method the extension can serve but nobody advertises simply does not exist.
#: ``scroll`` and ``logs`` are bridge-only capabilities (cmux degrades with a
#: typed error); they still live here because the wire protocol is shared.
METHODS = (
    "open",
    "goto",
    "read",
    "snapshot",
    "screenshot",
    "click",
    "type",
    "close",
    "status",
    # tabs lists every live extension-owned surface. It exists because parallel
    # sessions now each open their OWN tab (open no longer reuses another
    # session's surface), so agents need read-only discovery of what is being
    # driven. Listed handles are REDACTED (nonce truncated): the full token is
    # the drive capability, granted only by the surface's own `open` response,
    # so the listing is genuinely awareness-only. Bridge-only, like
    # scroll/logs: cmux has no multi-surface registry.
    "tabs",
    "scroll",
    "logs",
    # Site-permission flow (agent-legible approvals). ``request_access`` raises
    # the pending approval in the extension and returns immediately;
    # ``await_access`` blocks for a BOUNDED slice (the extension caps it well
    # under the command timeout) and the tool loops slices client-side. Split
    # this way because the old design — one navigation RPC that silently sat
    # on the 60 s popup prompt — expired unseen (the agent never got a turn to
    # tell the user to look at the popup) and made the session client time out
    # with a misleading "bridge unreachable" (sessions misdiagnosed the bridge
    # as broken and burned an hour on it).
    "request_access",
    "await_access",
    # Requester-bound cancellation removes only this session's exact-origin
    # pending entry; it cannot dismiss another session's consent prompt.
    "cancel_access",
    # Push a session title that arrived AFTER the tab was opened, so the tab
    # group stops wearing the label the session had at open time. A
    # conversation names itself asynchronously a second or two into its first
    # turn, which is usually after the opening "look at this page" already
    # created the group; every other command reconciles the group as a side
    # effect (worker.ts dispatch), but an open -> screenshot -> close session
    # issues no later command and so never self-healed. Presentation only: it
    # drives no tab, reads no page, and returns nothing but the applied label.
    "retitle",
)


#: How long the extension's approval popup gives the user to answer an origin
#: prompt before auto-denying with a typed ORIGIN_DENIED (origins.ts consumes
#: the generated copy in protocol.gen.ts). Milliseconds because it feeds a
#: chrome ``setTimeout`` directly.
#:
#: Timeout-chain invariant (finding A3): extension deny (60 s) < daemon prompt
#: window (65 s) < session client timeout (base command timeout + prompt window
#: + margin, backend.py). Each layer must outlive the one below it so the
#: innermost deadline always wins the race and the session receives a TYPED
#: answer (origin_denied / nav_timeout / result) instead of a transport
#: timeout. When the session client fired first (it used a flat 30–35 s), a
#: healthy daemon waiting on a human was misreported as "bridge unreachable"
#: and a QA session (transcript 0ee4974ba84a) burned an hour restarting a
#: daemon that was fine. All three constants live in or derive from this
#: module so the relationship cannot drift.
ORIGIN_PROMPT_TIMEOUT_MS = 60_000

#: Per-method base budgets for a command the extension is actively serving.
#: The daemon enforces these; the session client derives its own longer
#: HTTP timeout from them (backend.py) so the daemon's typed timeout always
#: arrives before the client gives up.
COMMAND_TIMEOUTS = {
    "open": 30.0,
    "goto": 30.0,
    "click": 25.0,
    "type": 25.0,
    "read": 20.0,
    "snapshot": 20.0,
    "screenshot": 20.0,
    "close": 20.0,
    "status": 20.0,
    # tabs, like status, names no tab and does no navigation: it enumerates the
    # extension's surface map and prunes dead entries, a handful of chrome.tabs
    # calls. It rides the same global lock key (no ``tab`` param) so a listing
    # cannot interleave with an in-flight open's map write.
    "tabs": 20.0,
    # scroll waits briefly for the wheel/scrollIntoView to settle and re-reads
    # position; logs just drains a per-tab ring buffer already in memory.
    "scroll": 20.0,
    "logs": 20.0,
    # request_access only writes the pending record and raises the prompt
    # surfaces — it returns immediately, never waiting on the human.
    "request_access": 20.0,
    # await_access polls the stored decision for one BOUNDED slice (the
    # extension caps itself at 20 s — access.ts AWAIT_SLICE_MS); the tool
    # loops slices client-side, so this stays an honest per-RPC bound and
    # never needs the awaiting_origin deadline-extension machinery above.
    "await_access": 25.0,
    "cancel_access": 20.0,
    # retitle touches chrome.tabGroups and nothing else — no navigation, no
    # settle, no debugger. It rides the ordinary floor rather than a tighter
    # bound because the group queue it joins is shared and briefly serialises
    # behind an in-flight open's own reconcile.
    "retitle": 20.0,
}

#: Extra budget granted to a command that is BLOCKED on a human origin
#: decision, on top of the base command timeout. The extension gives the user
#: 60 s to answer (ORIGIN_PROMPT_TIMEOUT_MS above); without this the 25–30 s
#: command timeout fired first, so a user who took longer than that got a
#: spurious tool failure while the tab navigated anyway against a surface the
#: session had written off (finding A3). Derived slightly above the extension's
#: deny-timeout so that deny wins the race and returns a typed ORIGIN_DENIED
#: rather than this firing blind.
ORIGIN_PROMPT_WINDOW_S = ORIGIN_PROMPT_TIMEOUT_MS / 1000 + 5.0


class ErrorCode(StrEnum):
    EXTENSION_DISCONNECTED = "extension_disconnected"
    NOT_PAIRED = "not_paired"
    TAB_CLOSED = "tab_closed"
    NAV_FAILED = "nav_failed"
    NAV_TIMEOUT = "nav_timeout"
    ELEMENT_NOT_FOUND = "element_not_found"
    ORIGIN_DENIED = "origin_denied"
    ORIGIN_PROMPT_PENDING = "origin_prompt_pending"
    # A top-level open/goto to an origin the user has not approved. Raised
    # EARLY, before any prompt exists, so the agent can run the explicit
    # request_access -> notify user -> await_access flow instead of blocking a
    # navigation on a popup prompt the user never saw.
    ORIGIN_NOT_ALLOWED = "origin_not_allowed"
    DEBUGGER_CONFLICT = "debugger_conflict"
    # The extension refuses to open more concurrent tabs than its cap (see
    # MAX_SURFACES in extension/src/state.ts): parallel sessions each own a
    # tab now, and without a bound an agent fleet could spray tabs into the
    # user's real browser. Typed so the tool can tell the agent to close one.
    ACCESS_QUEUE_FULL = "access_queue_full"
    TAB_LIMIT = "tab_limit"
    # A bare `close` while several tabs are open: the request is
    # under-specified, not a bridge fault, so it must not render as an
    # "internal" bridge error (review finding n1). The message carries the
    # REDACTED live handles so the caller can pick its own.
    TAB_AMBIGUOUS = "tab_ambiguous"
    BUSY = "busy"
    PROTO_MISMATCH = "proto_mismatch"
    INTERNAL = "internal"


class WireModel(BaseModel):
    """Strict envelopes make version skew fail at the boundary, not later."""

    model_config = ConfigDict(extra="forbid")


class Request(WireModel):
    id: str = Field(min_length=1)
    method: str = Field(min_length=1)
    params: dict[str, Any] = Field(default_factory=dict)


class ErrorDetail(WireModel):
    code: ErrorCode
    message: str
    data: dict[str, Any] = Field(default_factory=dict)


class Response(WireModel):
    id: str
    ok: bool
    result: dict[str, Any] | None = None
    error: ErrorDetail | None = None


class Hello(WireModel):
    event: Literal["hello"] = "hello"
    proto: int
    token: str = ""
    extension_version: str
    browser: str


class HelloAck(WireModel):
    event: Literal["hello_ack"] = "hello_ack"
    proto: int = PROTO_VERSION
    paired: bool


class PairRequest(WireModel):
    event: Literal["pair"] = "pair"
    code: str = Field(pattern=r"^[0-9]{6}$")


class PairResult(WireModel):
    event: Literal["pair_result"] = "pair_result"
    ok: bool
    token: str = ""
    message: str = ""


class Ping(WireModel):
    event: Literal["ping"] = "ping"


class Pong(WireModel):
    event: Literal["pong"] = "pong"


class TabClosed(WireModel):
    """Extension -> daemon: one driven tab is gone.

    Emitted from the extension's top-level ``chrome.tabs.onRemoved`` /
    ``onReplaced`` listeners and on an explicit ``close``, so a tab closed by
    the USER clears the daemon's driven record too. Nothing sent this event
    before, which is why ``status`` could advertise a tab that had been closed
    hours earlier. ``tab`` names the surface so one session's close cannot
    blank another session's still-live tab; an empty value means "unknown",
    which the daemon treats as clear-all.
    """

    event: Literal["tab_closed"] = "tab_closed"
    tab: str = ""


class TabUpdate(WireModel):
    """Extension -> daemon: the driven tab navigated. Lets the daemon report the
    current page to the Connected popup without an extra RPC (finding U3).

    ``tab`` is the surface handle: driven pages are tracked PER TAB, because a
    single global slot showed whichever tab was touched last as though it were
    the one bound tab. Defaulted for compatibility with an older extension that
    sent no handle.
    """

    event: Literal["tab_update"] = "tab_update"
    tab: str = ""
    url: str = ""
    title: str = ""


class AwaitingOrigin(WireModel):
    """Extension -> daemon: a command is blocked on a human origin decision, so
    the daemon extends that command's deadline past the base timeout (A3) and
    can surface the pending site (U2)."""

    event: Literal["awaiting_origin"] = "awaiting_origin"
    id: str
    origin: str = ""


class AwaitingOriginCleared(WireModel):
    """Extension -> daemon: a previously announced command is NO LONGER blocked
    on a human origin decision — its queue entry expired, was cancelled, or was
    decided without a response the daemon will see. The daemon pops its record
    so /health stops echoing a prompt the extension no longer shows; without
    this the echo outlived the queue entry and the popup looped on a stale
    request it could never resolve."""

    event: Literal["awaiting_origin_cleared"] = "awaiting_origin_cleared"
    id: str


class Unpair(WireModel):
    """Extension -> daemon: the options page revoked pairing, so the daemon must
    drop the live socket, not merely the next reconnect (findings A5/U1)."""

    event: Literal["unpair"] = "unpair"


class OriginDecision(WireModel):
    event: Literal["origin_decision"] = "origin_decision"
    origin: str
    decision: Literal["once", "always", "deny"]
