#!/usr/bin/env node
/* Regenerate src/psl.gen.ts from the Public Suffix List.
 *
 * The "All pages on this domain" grant is keyed by the registrable domain
 * (eTLD+1), and computing that WITHOUT a bundled list fails open: any suffix
 * the extension does not know (`gov.xx`, `github.io`) would collapse to its
 * last two labels and a single approval would cover every tenant under it.
 * The list is therefore bundled at build time and refreshed per release
 * (docs/store/submission-checklist.md) rather than fetched at runtime, which
 * would need a network permission and a fallback for the offline case.
 *
 * Both the ICANN and PRIVATE sections are kept: PRIVATE is what makes
 * `me.github.io` its own registrable domain instead of granting `*.github.io`,
 * which is exactly the multi-tenant hosting case the option must not widen
 * across. Chrome's own cookie/site boundary uses both sections.
 *
 * Each rule is passed through `url.domainToASCII` so IDN rules compare equal
 * to the punycode `URL.hostname` yields at runtime. Comments and blank lines
 * are dropped; the rule set is emitted as ONE newline-joined string constant
 * (parsed lazily into a Set on first use) so esbuild keeps it as a single
 * literal rather than thousands of array elements.
 *
 * Usage: node scripts/gen-psl.mjs [--check]
 *   --check exits non-zero when src/psl.gen.ts differs from a fresh fetch.
 */
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { domainToASCII } from "node:url";

const SOURCE = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUT = resolve(import.meta.dirname, "..", "src", "psl.gen.ts");

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`fetch ${SOURCE}: ${response.status}`);
const raw = await response.text();

const rules = [];
let section = "";
for (const line of raw.split("\n")) {
  const text = line.trim();
  if (text.startsWith("// ===BEGIN ICANN DOMAINS===")) section = "icann";
  if (text.startsWith("// ===BEGIN PRIVATE DOMAINS===")) section = "private";
  if (!text || text.startsWith("//")) continue;
  if (!section) continue;
  const rule = text.split(/\s/, 1)[0];
  // `!` (exception) and `*.` (wildcard) prefixes are not hostname labels;
  // strip them for the IDN conversion and put them back.
  const prefix = rule.startsWith("!") ? "!" : rule.startsWith("*.") ? "*." : "";
  const ascii = domainToASCII(rule.slice(prefix.length));
  if (!ascii) throw new Error(`rule did not convert to ASCII: ${rule}`);
  rules.push(prefix + ascii);
}
if (rules.length < 5000) throw new Error(`suspiciously short list: ${rules.length} rules`);

const stamp = new Date().toISOString().slice(0, 10);
const body =
  `// GENERATED by scripts/gen-psl.mjs from ${SOURCE}. Do not edit.\n` +
  `// Refresh per extension release (docs/store/submission-checklist.md): a\n` +
  `// suffix registered after this date is treated as a registrable domain\n` +
  `// and a domain grant on it would cover every name beneath it.\n` +
  `export const PSL_GENERATED_AT = "${stamp}";\n` +
  `export const PSL_RULE_COUNT = ${rules.length};\n` +
  `export const PSL_RULES = ${JSON.stringify(rules.join("\n"))};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(OUT, "utf8").catch(() => "");
  // The date line legitimately differs between runs; compare the rules only.
  const strip = (text) => text.replace(/^export const PSL_GENERATED_AT = .*$/m, "");
  if (strip(current) !== strip(body)) {
    console.error("src/psl.gen.ts is stale; run node scripts/gen-psl.mjs");
    process.exit(1);
  }
  console.log(`src/psl.gen.ts matches upstream (${rules.length} rules)`);
} else {
  await writeFile(OUT, body);
  console.log(`wrote ${OUT}: ${rules.length} rules, generated ${stamp}`);
}
