#!/usr/bin/env python3
"""Regenerate the committed i18n artifacts, or check them for drift.

WHAT THIS OWNS (all of it generated, all of it committed):

* ``local_operator/i18n/data/plural_rules.json`` + ``formats.json`` — emitted by
  ``scripts/i18n/emit.mjs`` from Node `Intl` (see that file for determinism);
* ``local_operator/i18n/keys/<namespace>.py`` — one function per message key,
  typed from the message's own placeholders (RFC §2.4: per-key functions, NOT
  `@overload`s — the overload shape did not finish a 5,000-key typecheck);
* ``local_operator/i18n/data/shipped.json`` — the shipped-locale set computed
  from ``i18n/ledger.json`` (§6: a locale ships iff every namespace has a
  ledger entry that passed against the CURRENT en source hash). ``en`` is
  always shipped.

WHY A DRIFT CHECK. These are generated-but-committed, so a hand edit or a
catalogue change without regeneration would ship tables that disagree with the
catalogues. ``--check`` re-runs everything into a temp directory and requires
byte-identical output; CI runs it as the cheap `i18n` job (and locally:
``.venv/bin/python scripts/i18n/generate.py --check``).

DETERMINISM RULES, learned from `scripts/gen_agent_seed_manifest.py`: no clock
reads, no environment reads, sorted iteration everywhere, and the emitter is
invoked with a fixed locale set. The only input that can move the output is a
change to the catalogue files, the emitter, or the ledger — which is exactly
what should void the check.
"""

from __future__ import annotations

import argparse
import json
import keyword
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
# Scripts under scripts/ read the tree they live in regardless of which venv
# launched them (a console script's sys.path[0] is .venv/bin, not the cwd).
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from local_operator.i18n import catalogues  # noqa: E402
from local_operator.i18n import runtime as msg_runtime  # noqa: E402
from local_operator.i18n.resolve import SUPPORTED_LOCALES  # noqa: E402

EMITTER = REPO / "scripts" / "i18n" / "emit.mjs"
DATA_DIR = REPO / "local_operator" / "i18n" / "data"
KEYS_DIR = REPO / "local_operator" / "i18n" / "keys"
LEDGER = REPO / "i18n" / "ledger.json"

GENERATED_HEADER = (
    '"""GENERATED by scripts/i18n/generate.py — do not edit by hand.\n\n'
    "Regenerate with `.venv/bin/python scripts/i18n/generate.py`; CI rejects\n"
    "drift (`generate.py --check`). The one function per message key is the\n"
    "shape RFC §2.4 proved: a mistyped key or kwarg fails pyright.\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
)


def _run_emitter(out_dir: Path) -> None:
    """Run the Node emitter into ``out_dir``; a missing node is a loud failure."""
    try:
        result = subprocess.run(
            ["node", str(EMITTER), "--out", str(out_dir)],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise SystemExit(
            "generate.py: `node` is required to emit the Intl tables (the emitter "
            "is scripts/i18n/emit.mjs). Install Node or run this via CI, which has it."
        ) from exc
    if result.returncode != 0:
        raise SystemExit(
            f"generate.py: emit.mjs failed ({result.returncode}):\n{result.stderr or result.stdout}"
        )


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _identifier(name: str) -> str:
    """A valid Python identifier for a key segment or argument name.

    Two legal catalogue shapes would otherwise emit SYNTAX ERRORS that the
    text-comparing drift check cannot see (round-1 m2): a digit-leading
    segment (`demo.bad.2fa` -> `def 2fa`) and a Python-keyword argument
    (`{class, select, ...}` -> `*, class: str`). The Python spelling moves; the
    MESSAGE KEY and the argument name in the Msg body stay exactly as the
    catalogue spells them, so the wire contract is untouched.
    """
    safe = name
    if safe and safe[0].isdigit():
        safe = "_" + safe
    if keyword.iskeyword(safe):
        safe += "_"
    return safe


def _fn_name(namespace: str, key: str) -> str:
    suffix = key[len(namespace) + 1 :] if key.startswith(namespace + ".") else key
    return _identifier(suffix.replace(".", "_").replace("-", "_"))


def _param_types(message: str) -> list[tuple[str, str]]:
    """``(name, annotation)`` per argument, in first-appearance order."""
    annotations = {
        "plural": "int | float",
        "number": "int | float",
        "date": "datetime",
        "time": "datetime",
    }
    return [
        (name, annotations.get(kind, "str"))
        for name, kind in msg_runtime.message_arguments(message)
    ]


def _render_keys_module(namespace: str, messages: dict[str, str]) -> str:
    lines = [GENERATED_HEADER]
    body: list[str] = []
    needs_datetime = False
    seen_fnames: dict[str, str] = {}
    for key in sorted(messages):
        params = _param_types(messages[key])
        if any(annotation == "datetime" for _, annotation in params):
            needs_datetime = True
        fname = _fn_name(namespace, key)
        # Two legal keys can sanitise to one function name (`demo.x.class` /
        # `demo.x.class_`, `demo.x.foo-bar` / `demo.x.foo_bar`); emitting both
        # would silently SHADOW one def (round-2 m5) — refuse instead, like the
        # keyword-argument collision below.
        if fname in seen_fnames:
            raise SystemExit(
                f"generate.py: {namespace}: keys {seen_fnames[fname]!r} and {key!r} emit the "
                f"same function name {fname!r}; rename one in the catalogue"
            )
        seen_fnames[fname] = key
        if params:
            # Sanitise the ARGUMENT identifiers too (m2) and refuse a
            # sanitisation collision loudly rather than emitting duplicate
            # kwargs the compiler would reject far from the cause.
            sanitised = [_identifier(name) for name, _ in params]
            if len(set(sanitised)) != len(sanitised):
                raise SystemExit(
                    f"generate.py: {namespace}: arguments of {key!r} sanitise to "
                    f"duplicate identifiers {sanitised}; rename one in the catalogue"
                )
            signature = ", ".join(f"*, {safe}: {ann}" for safe, (_, ann) in zip(sanitised, params))
            pairs = ", ".join(f'"{name}": {safe}' for safe, (name, _) in zip(sanitised, params))
        else:
            signature = ""
            pairs = ""
        body.append(f'def {fname}({signature}) -> Msg:\n    return Msg("{key}", {{{pairs}}})\n')
    if body:
        # Imports only when something uses them: a namespace stub with zero
        # keys yet must not trip flake8's unused-import rule (F401) — the
        # ratchet gate runs over exactly these files.
        if needs_datetime:
            lines.append("from datetime import datetime\n\n")
        lines.append("from ..messages import Msg\n\n\n")
        lines.append("\n\n".join(body))
    return "".join(lines).rstrip() + "\n"


def _render_keys_init(modules: list[str]) -> str:
    # The modules are IMPORTED, not just listed in `__all__`: pyright reads an
    # `__all__` naming a module the package never imported as a defect
    # (reportUnsupportedDunderAll), and callers reaching
    # `keys.wire_errors.model_unavailable` should not need a second import.
    sorted_modules = sorted(modules)
    import_lines = "\n".join(f"    {name}," for name in sorted_modules)
    listed = "\n".join(f'    "{name}",' for name in sorted_modules)
    return (
        GENERATED_HEADER + f"from . import (\n{import_lines}\n)\n\n" + f"__all__ = [\n{listed}\n]\n"
    )


def _shipped_locales() -> list[str]:
    """The shipped set: en, plus locales with complete, fresh ledger passes.

    Freshness is the §6 gate: an entry counts iff its ``source_sha256`` equals
    the CURRENT hash of the en file for that namespace. A stale entry is not a
    pass; a locale with any namespace missing or stale is not shipped.
    """
    shipped: set[str] = {"en"}
    if not LEDGER.is_file():
        return [loc for loc in SUPPORTED_LOCALES if loc in shipped]
    ledger = _read_json(LEDGER)
    entries = ledger.get("entries", []) if isinstance(ledger, dict) else []
    en_namespaces = catalogues.namespaces("en")
    by_locale: dict[str, dict[str, dict[str, Any]]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        locale = entry.get("locale")
        namespace = entry.get("namespace")
        if isinstance(locale, str) and isinstance(namespace, str):
            by_locale.setdefault(locale, {})[namespace] = entry
    for locale in SUPPORTED_LOCALES:
        if locale == "en":
            continue
        record = by_locale.get(locale)
        if not record:
            continue
        if all(
            (entry := record.get(namespace)) is not None
            and entry.get("status") == "passed"
            and entry.get("source_sha256") == catalogues.catalogue_sha256("en", namespace)
            for namespace in en_namespaces
        ):
            shipped.add(locale)
    return [loc for loc in SUPPORTED_LOCALES if loc in shipped]


def _render_shipped() -> str:
    payload = {"schema": 1, "locales": _shipped_locales()}
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _planned_files(emitted: Path) -> dict[Path, str]:
    """Everything generation should produce: path -> content (strings)."""
    planned: dict[Path, str] = {
        DATA_DIR / "plural_rules.json": (emitted / "plural_rules.json").read_text(encoding="utf-8"),
        DATA_DIR / "formats.json": (emitted / "formats.json").read_text(encoding="utf-8"),
        DATA_DIR / "shipped.json": _render_shipped(),
    }
    en_dir = catalogues.catalogue_root() / "en"
    modules: list[str] = []
    for namespace in catalogues.namespaces("en"):
        messages = _read_json(en_dir / f"{namespace}.json")
        module = namespace.replace(".", "_").replace("-", "_")
        modules.append(module)
        planned[KEYS_DIR / f"{module}.py"] = _render_keys_module(namespace, messages)
    planned[KEYS_DIR / "__init__.py"] = _render_keys_init(modules)
    return planned


def _check(planned: dict[Path, str]) -> int:
    stale: list[str] = []
    for path, content in sorted(planned.items(), key=lambda item: str(item[0])):
        rel = path.relative_to(REPO)
        if not path.is_file():
            stale.append(f"missing: {rel}")
            continue
        if path.read_text(encoding="utf-8") != content:
            stale.append(f"changed: {rel}")
    # ORPHANS, the failure a plan-vs-plan diff can never see (round-1 n4): a
    # namespace rename/removal leaves `keys/<old>.py` (or a data file) behind,
    # nothing regenerates it, and the diff stays green while the package grows
    # a module no catalogue knows about. Checked for the two generated dirs.
    for directory, pattern in ((KEYS_DIR, "*.py"), (DATA_DIR, "*.json")):
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob(pattern)):
            if path not in planned:
                stale.append(f"orphaned: {path.relative_to(REPO)}")
    if stale:
        print("generate.py --check: committed artifacts are stale — regenerate with")
        print("  .venv/bin/python scripts/i18n/generate.py")
        print(
            "(the emitter is pinned to Node 24 — CI's setup-node major — and its output "
            "is normalised to be node-major stable; see the note in scripts/i18n/emit.mjs)"
        )
        for line in stale:
            print(f"  {line}")
        return 1
    print(f"generate.py --check: {len(planned)} artifact(s) byte-identical")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a temp dir and fail on any byte difference (CI mode)",
    )
    args = parser.parse_args(argv)

    with tempfile.TemporaryDirectory(prefix="i18n-emit-") as td:
        emitted = Path(td)
        _run_emitter(emitted)
        planned = _planned_files(emitted)
        if args.check:
            return _check(planned)
        for path, content in planned.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
