/**
 * The session's spend and context readings — one module, ported not designed.
 *
 * The phone's session screen answers two glance questions the desktop strip
 * already answers ("what has this cost", "how full is the window"), and the
 * rule for both is that the spelling is the PYTHON's. Two spellings of one
 * number is two answers to one question, so this module holds the bundle's
 * only copy, and `spend-context.parity.json` — generated by
 * `scripts/generate_spend_context_parity.py` — pins every case against the
 * live Python in `tests/unit/mobile/test_tui_bridge.py` and this bundle's
 * `spend-context.test.ts`.
 *
 * Sources, by symbol:
 *
 *   - `tui/costs.py::format_usd` / `micro_from_usd` — the ONE money ladder,
 *     including `<$0.0001` for a nonzero sub-half-micro figure. The float half
 *     is what the band reaches through `status_line.format_cost`; the wrapper
 *     itself is not ported because a wire value is coerced to finite before it
 *     gets here, so the wrapper's non-finite fallback is unreachable.
 *   - `FrontendSessionState.cumulative_cost` / `cumulative_cost_knowledge` —
 *     which ledger wins: the owner ledger when it reports knowledge AT ALL
 *     (including `unknown`), the compatibility `child_costs` map otherwise,
 *     and NEVER both (summing them double-counts swept work and live
 *     descendants). `partial`/`floor` rungs mark the figure as a lower bound;
 *     `partial`/`floor` on the parent wins over anything a child says.
 *   - `tui/app.py::_spend_text` — zero renders NOTHING (a confident `$0.0000`
 *     over billed tokens is the more expensive lie); the floor mark is `\u2265`;
 *     and when the total is unknown but tokens were billed, the band writes
 *     `$—` — "we spent something we cannot price", distinct from "we have not
 *     spent". The `usage` pair below is that billed signal.
 *   - `status_line.py::context_spelling` / `context_semantic_color` (and its
 *     two band tuples) + `frontend_state.py::format_context_tokens` /
 *     `format_window` — the reading itself. A percentage needs `window > 0`;
 *     sub-0.05% stays `<0.1%`; a rounded `0%` over a non-zero reading is
 *     refused. The colour is the warmer of an absolute token ladder and a
 *     proportional one.
 *
 * What would make this mirror wrong: any of those moving, or `CostKnowledge`
 * gaining a rung (a new rung would land in neither the `partial` nor the
 * `floor` set and would silently render as exact).
 *
 * NOT ported, deliberately: `max_context_window` / `context_breakdown` /
 * `usage_components` (no phone surface yet), the tooltip sentences (a touch
 * screen has no hover), and the `nodec`/`short` context forms (they exist for
 * the TUI's narrow subagent rows; the phone renders one reading).
 */
import type { SessionProjection } from "../types";
import { pyFixed } from "./fixed-point";

/** `CostKnowledge` (`session/frontend_state.py`), as the wire carries it. */
export type CostKnowledge = "unknown" | "exact" | "partial" | "floor";

/** `RESTORED_COST_PREFIX` — the mark for a figure that is a lower bound. */
export const FLOOR_MARK = "\u2265";

/**
 * `UNKNOWN_COST_CELL` — tokens were billed at a price nobody could resolve.
 *
 * Distinct from "no spend to show": the session DID spend, and the app cannot
 * say how much.
 */
export const UNPRICEABLE_TEXT = "$\u2014";

/** Below this many micro-USD the ladder prints `<$0.0001` (`costs.py`). */
const SUB_CENT_VISIBLE_MICRO = 50;

/** The five accounting fields this module reads, as the wire delivers them. */
export type SessionSpendInput = Pick<
	SessionProjection,
	| "cumulative_parent_cost"
	| "child_costs"
	| "subagent_cost"
	| "subagent_cost_knowledge"
	| "cost_knowledge"
>;

/** The LAST receipt's token pair — the billed signal for the `$—` case. */
export type SessionUsage = Record<string, number> | null | undefined;

export type SessionSpend = {
	/** `cumulative_cost`: parent plus children, or null when neither is known. */
	total: number | null;
	/** `cumulative_cost_knowledge`, defaulted to `unknown` on a malformed wire. */
	knowledge: CostKnowledge;
	/** True when `knowledge` marks the total as a lower bound (`partial`/`floor`). */
	isFloor: boolean;
	/**
	 * What the screen prints, mark included. `""` when there is nothing to
	 * show, which is `_spend_text`'s zero and null policy in one value — every
	 * caller hides the segment on the same test rather than each inventing its
	 * own.
	 */
	text: string;
};

/** Coerce a wire number, treating a non-finite or absent value as unknown. */
function finite(value: unknown): number | null {
	return typeof value === "number" && Number.isFinite(value) ? value : null;
}

/** Normalise a wire value to a rung this app knows, or `unknown`. */
function rung(value: unknown): CostKnowledge {
	return value === "exact" || value === "partial" || value === "floor"
		? value
		: "unknown";
}

/**
 * The children's contribution (`cumulative_cost`'s `children`).
 *
 * The owner ledger is a SINGLE contribution and never summed with the
 * compatibility rows, which omit swept work and live descendants. Note the
 * switch is `subagent_cost_knowledge != null`: an owner that says "I do not
 * know what my children cost" is still the authority on the question.
 */
function childTotal(state: SessionSpendInput): number | null {
	if (state.subagent_cost_knowledge != null) return finite(state.subagent_cost);
	const rows = state.child_costs;
	if (!rows) return null;
	const values = Object.values(rows).filter(
		(value): value is number =>
			typeof value === "number" && Number.isFinite(value),
	);
	// An EMPTY map is "no children", not "children cost zero". The distinction
	// survives into the total, where no children plus a null parent is null
	// rather than 0.0 — which is what keeps a fresh session's segment absent.
	return values.length > 0 ? values.reduce((a, b) => a + b, 0) : null;
}

/** True for the two rungs that mark a figure as a lower bound. */
function isFloorKnowledge(knowledge: CostKnowledge): boolean {
	return knowledge === "floor" || knowledge === "partial";
}

/**
 * `cumulative_cost_knowledge`, field for field.
 *
 * The order is load-bearing: the session's OWN `partial`/`floor` wins before
 * the owner ledger is consulted at all, because a parent figure that is
 * already a floor cannot be made exact by a child that happens to be known.
 */
export function cumulativeCostKnowledge(state: SessionSpendInput): CostKnowledge {
	const own = rung(state.cost_knowledge);
	if (own === "partial" || own === "floor") return own;
	const child = state.subagent_cost_knowledge;
	if (child === "partial") return "partial";
	// An owner that reports `unknown` degrades the total only when there are
	// children we can actually see. With no rows the unknown is about nothing.
	if (
		child === "unknown" &&
		state.child_costs &&
		Object.keys(state.child_costs).length > 0
	)
		return "partial";
	return own;
}

/**
 * `micro_from_usd`: the exact integer micro-USD of a float dollar figure.
 *
 * `null` means "not a figure this ladder can take" — non-finite, or not a
 * number at all. The rounding is Python's `round()`: half to EVEN on the
 * exact value, which `pyFixed` already implements, so the tie behaviour
 * matches for free (a `.5` micro lands on the even neighbour, not away from
 * zero).
 */
export function microFromUsd(cost: unknown): number | null {
	if (typeof cost !== "number" || !Number.isFinite(cost)) return null;
	const micro = Number(pyFixed(cost * 1_000_000, 0));
	// `Number("-0")` is `-0`, and Python's `int(round(x))` has no negative
	// zero: a value between -0.5 and 0 micros is plainly `0`. Normalise rather
	// than leaking a signed zero into comparisons and sums.
	return micro === 0 ? 0 : micro;
}

/**
 * `format_usd`: the ONE dollar ladder, from an EXACT integer micro-USD amount.
 *
 * Ladder (rounding, never truncation):
 *   - `$1.90` above a dollar, `$0.213` above a cent, `$0.0042` below it;
 *   - a NONZERO amount under half a ten-thousandth of a dollar renders
 *     `<$0.0001` — the one spelling where the ladder would otherwise lie;
 *   - zero renders `$0.0000`, unchanged: for a genuine zero that spelling is
 *     correct, and the band's zero policy drops the segment entirely.
 */
export function formatUsd(micro: number): string {
	if (micro < SUB_CENT_VISIBLE_MICRO) return micro > 0 ? "<$0.0001" : "$0.0000";
	const cost = micro / 1_000_000;
	if (cost < 0.01) return `$${pyFixed(cost, 4)}`;
	if (cost < 1) return `$${pyFixed(cost, 3)}`;
	return `$${pyFixed(cost, 2)}`;
}

/**
 * `cumulative_cost` plus `_spend_text`'s spelling, for one projection.
 *
 * `usage` answers the `billed` question: did this turn bill tokens at a price
 * that could not be resolved. When it did and the total is null, print `$—`
 * rather than nothing, because "we spent something we cannot price" is a
 * different fact from "we have not spent".
 */
export function sessionSpend(
	state: SessionSpendInput,
	usage?: SessionUsage,
): SessionSpend {
	const parent = finite(state.cumulative_parent_cost);
	const children = childTotal(state);
	const knowledge = cumulativeCostKnowledge(state);
	const isFloor = isFloorKnowledge(knowledge);
	const total =
		parent === null && children === null
			? null
			: (parent ?? 0) + (children ?? 0);

	if (total === null) {
		const billed = Boolean(
			usage && (usage.input_tokens || usage.output_tokens),
		);
		return {
			total: null,
			knowledge,
			isFloor,
			text: billed ? UNPRICEABLE_TEXT : "",
		};
	}
	// `if not spend: return ""`. Python's falsiness covers 0.0 and -0.0, and
	// this is the policy paragraph of `_spend_text`: a zero spends no segment,
	// because an unpriced model reaching the band as 0.0 is exactly the case
	// that would otherwise print a confident `$0.0000` over billed tokens.
	if (!total) return { total, knowledge, isFloor, text: "" };
	const micro = microFromUsd(total);
	// `finite` above already refused non-finite totals, so a null micro is
	// unreachable; keeping the empty spelling anyway is this module's contract
	// of never inventing a figure rather than a live branch.
	const digits = micro === null ? "" : formatUsd(micro);
	return {
		total,
		knowledge,
		isFloor,
		text: `${isFloor ? FLOOR_MARK : ""}${digits}`,
	};
}

/** The semantic rungs, warmest first — `_CONTEXT_COLOR_RANK`. */
export type ContextRung = "signal" | "label" | "danger";

/** Warmest first, so a union of two ladders can be resolved by rank. */
const RANK: readonly ContextRung[] = ["danger", "label", "signal"];

/** Colour of a reading below every band — `CONTEXT_COLOR_BASE`. */
export const CONTEXT_COLOR_BASE: ContextRung = "signal";

/**
 * `CONTEXT_COLOR_BANDS`: absolute token counts, largest first.
 *
 * Absolute because the cost they warn about is absolute — 300k tokens is slow
 * and expensive to re-send whether the window is 1M or 200k.
 */
export const CONTEXT_COLOR_BANDS: readonly (readonly [number, ContextRung])[] =
	[
		[500_000, "danger"],
		[200_000, "label"],
	];

/**
 * `CONTEXT_COLOR_WINDOW_BANDS`: fractions of the window, applied as a UNION
 * with the absolute ladder above.
 *
 * The proportional half is what makes a small window legible: at 200k and
 * below the absolute rungs are unreachable, so without it the reading would
 * stay calm through 100% full while compaction was already due.
 */
export const CONTEXT_COLOR_WINDOW_BANDS: readonly (readonly [
	number,
	ContextRung,
])[] = [
	[0.8, "danger"],
	[0.55, "label"],
];

/**
 * `context_semantic_color(tokens, window)` — the warmer of the two ladders.
 *
 * `window <= 0` (unknown) falls back to the absolute ladder alone, since a
 * percentage needs a denominator. Both comparisons are strictly greater-than,
 * so a value sitting exactly on a boundary keeps the calmer colour and a
 * number hovering there does not flicker between two hues.
 */
export function contextSemanticColor(tokens: number, window = 0): ContextRung {
	let color: ContextRung = CONTEXT_COLOR_BASE;
	for (const [threshold, candidate] of CONTEXT_COLOR_BANDS) {
		if (tokens > threshold) {
			color = candidate;
			break;
		}
	}
	if (window > 0) {
		for (const [fraction, candidate] of CONTEXT_COLOR_WINDOW_BANDS) {
			if (tokens > window * fraction) {
				// Warmest wins: rank is warmest-first, so a lower index is warmer.
				if (RANK.indexOf(candidate) < RANK.indexOf(color)) color = candidate;
				break;
			}
		}
	}
	return color;
}

/**
 * `format_context_tokens`: `12.4k` / `1.2m` style, plain under 1k.
 *
 * Lower-case `m` here and capital `M` in `formatWindow` below is not a typo on
 * either side — it is the Python, where a MEASUREMENT and a LABEL are spelled
 * differently on purpose.
 */
export function formatContextTokens(tokens: number): string {
	if (tokens >= 1_000_000) return `${pyFixed(tokens / 1_000_000, 1)}m`;
	if (tokens >= 1_000) return `${pyFixed(tokens / 1_000, 1)}k`;
	return String(tokens);
}

/**
 * `format_window`: abbreviate the denominator — `1M`, `200k`.
 *
 * A whole window renders without a decimal, because the denominator is a
 * label rather than a measurement.
 */
export function formatWindow(window: number): string {
	if (window >= 1_000_000) {
		const scaled = window / 1_000_000;
		return scaled === Math.trunc(scaled)
			? `${pyFixed(scaled, 0)}M`
			: `${pyFixed(scaled, 1)}M`;
	}
	if (window >= 1_000) {
		const scaled = window / 1_000;
		return scaled === Math.trunc(scaled)
			? `${pyFixed(scaled, 0)}k`
			: `${pyFixed(scaled, 1)}k`;
	}
	return String(window);
}

/**
 * `context_spelling(tokens, window)` — the band's `full` form.
 *
 * Empty when there is nothing to report, so every caller's segment disappears
 * on the same test. A percentage needs a denominator: with no window the spend
 * is reported against an explicit unknown (`12.4k/—`) rather than against an
 * invented one, and a rounded `0%` over a non-zero reading is refused in all
 * of them.
 */
export function contextSpelling(tokens: number, window: number): string {
	if (tokens <= 0) return "";
	if (window <= 0) return `${formatContextTokens(tokens)}/\u2014`;
	const percent = (tokens / window) * 100;
	if (percent < 0.05) return `<0.1%/${formatWindow(window)}`;
	return `${pyFixed(percent, 1)}%/${formatWindow(window)}`;
}

/** The four states a context reading can be in, named so the UI can branch. */
export type ContextStatus =
	/** No reading has arrived — a session that has not answered yet. */
	| "no-reading"
	/** Tokens are known, the window is not: a percentage is impossible. */
	| "window-unknown"
	/** Both known, and the tokens figure is the provider's settled receipt. */
	| "measured"
	/** Both known, and the tokens figure is the harness's own estimate. */
	| "estimate";

export type ContextReading = {
	status: ContextStatus;
	tokens: number | null;
	window: number | null;
	/** The rung, from the union of the two ladders. */
	rung: ContextRung;
	/** `context_spelling`'s `full` form, or `""` when there is nothing to say. */
	spelling: string;
};

/** The three context fields this module reads, as the wire delivers them. */
export type ContextInput = Pick<
	SessionProjection,
	"context_tokens" | "context_window" | "context_is_estimate"
>;

/**
 * One context reading, resolved from the canonical fields.
 *
 * Every unknown is a STATE rather than a zero: `no-reading` renders nothing,
 * and `window-unknown` renders absolute tokens with no percentage, because a
 * fraction of nothing is not a reading.
 */
export function contextReading(state: ContextInput): ContextReading {
	const rawTokens = state.context_tokens;
	const tokens =
		typeof rawTokens === "number" && Number.isFinite(rawTokens) && rawTokens > 0
			? rawTokens
			: null;
	const rawWindow = state.context_window;
	const window =
		typeof rawWindow === "number" && Number.isFinite(rawWindow) && rawWindow > 0
			? rawWindow
			: null;
	const rung = contextSemanticColor(tokens ?? 0, window ?? 0);
	if (tokens === null) {
		return {
			status: "no-reading",
			tokens: null,
			window,
			rung: CONTEXT_COLOR_BASE,
			spelling: "",
		};
	}
	if (window === null) {
		return {
			status: "window-unknown",
			tokens,
			window: null,
			rung,
			spelling: contextSpelling(tokens, 0),
		};
	}
	return {
		// The estimate marker is EXPLICIT rather than implied by a rounded
		// number: `context_is_estimate` is the owner's own statement about
		// whether the figure came from a provider receipt or from the harness's
		// count, and a reader deciding whether to compact deserves to know which.
		status: state.context_is_estimate ? "estimate" : "measured",
		tokens,
		window,
		rung,
		spelling: contextSpelling(tokens, window),
	};
}

/**
 * The estimate marker — the WORD `estimate`, or `""` when the figure is a
 * measurement (or absent).
 *
 * TWO PRECEDENTS, AND THE RULING THAT PICKED BETWEEN THEM. The TUI's
 * `/context` rows mark an estimated token count with a `~` glyph
 * (`serving.py`'s `estimated()` helper), and the phone's first cut copied it.
 * The desktop strip — this surface's stated information-design reference
 * (desktop-as-design-source) — appends the word `estimate` in `ink-dim`
 * instead, under a rule against hints: "The estimate marker is a WORD, not a
 * glyph or a dimmed colour … a tilde or a lighter ink is a hint the user has
 * to have been taught" (§ 8: every claim checkable). Design review round 1
 * (D2) ruled for the desktop convention on this surface; the `/context`
 * precedent is recorded here so the divergence reads as a decision rather
 * than an accident.
 *
 * The word is NOT part of the ported spelling — `reading.spelling` stays
 * character-for-character the Python's — and it renders as its own dim
 * segment beside the reading, because the qualifier describes the figure and
 * must not inherit the reading's rung colour. It replaces a single-string
 * composer (`contextDisplaySpelling`) that could not carry a two-tone marker.
 */
export function contextEstimateMarker(reading: ContextReading): string {
	return reading.status === "estimate" ? "estimate" : "";
}
