// GENERATED by python -m local_operator.browser_bridge.gen_ts. Do not edit.
// Vendored copy for local-operator-ui: protocol.gen.ts (wire declarations).
// Source of truth: local-operator local_operator/browser_bridge/protocol.py + gen_ts.py + extension/src/driver/*.ts (8 modules: access-flow.ts, access-queue.ts, ax-compact.ts, deadline.ts, errors.ts, origin-policy.ts, psl.gen.ts, scroll-expressions.ts)
// PROTO_VERSION: 1
// Inputs sha256: a12685a9c3d3fd5d7bc11fb1084d28ca76586253cbde6da3046faae112de2b49
// An INPUT hash, never a git SHA: a stamp over commits would go red on every
// commit that touched nothing this generator reads, and a gate that cries wolf
// gets deleted. Regenerate with `python -m local_operator.browser_bridge.gen_ts`;
// `--bundle-out DIR` is the same command pointed at another tree, which is how
// local-operator-ui's sync script generates its own checkout.
export const PROTO_VERSION = 1 as const;
// The extension version this runtime was developed and released alongside.
// ADVISORY ONLY: nothing is refused for being older (`MIN_SUPPORTED_PROTO` is
// the compatibility floor). Generated so the popup's update line and the
// daemon's agree by construction.
export const EXPECTED_EXTENSION_VERSION = '0.1.16' as const;
// The ONE spelling of the "a newer extension exists" advisory. `{have}` and
// `{want}` are the reported and the expected extension versions; the
// contingency is on the Chrome Web Store because nothing here can know what the
// store currently offers. Nothing is blocked by an older extension — the copy
// says so, and must keep saying so.
export const EXTENSION_UPDATE_NOTE = 'Browser extension {have} < {want} — update it in Chrome when a newer version is offered; nothing is blocked.';
// How long the approval popup waits for a human origin decision before
// auto-denying. Generated so the daemon's prompt window (this + margin) and
// the session client's HTTP timeout can never drift below it (finding A3).
export const ORIGIN_PROMPT_TIMEOUT_MS = 60000 as const;

export enum ErrorCode {
  EXTENSION_DISCONNECTED = 'extension_disconnected',
  NOT_PAIRED = 'not_paired',
  TAB_CLOSED = 'tab_closed',
  NAV_FAILED = 'nav_failed',
  NAV_TIMEOUT = 'nav_timeout',
  ELEMENT_NOT_FOUND = 'element_not_found',
  ORIGIN_DENIED = 'origin_denied',
  ORIGIN_PROMPT_PENDING = 'origin_prompt_pending',
  ORIGIN_NOT_ALLOWED = 'origin_not_allowed',
  DEBUGGER_CONFLICT = 'debugger_conflict',
  ACCESS_QUEUE_FULL = 'access_queue_full',
  TAB_LIMIT = 'tab_limit',
  TAB_AMBIGUOUS = 'tab_ambiguous',
  BUSY = 'busy',
  PROTO_MISMATCH = 'proto_mismatch',
  OWNER_REFUSED = 'owner_refused',
  EXTENSION_UNRESPONSIVE = 'extension_unresponsive',
  INTERNAL = 'internal',
}

export type Method = 'open' | 'goto' | 'read' | 'snapshot' | 'screenshot' | 'click' | 'type' | 'close' | 'status' | 'tabs' | 'scroll' | 'logs' | 'request_access' | 'await_access' | 'cancel_access' | 'retitle' | 'owner_recover' | 'owner_finish' | 'owner_retain' | 'owner_release';
// One buffered console/runtime log line, as `logs` returns it (newest last).
// `level` is normalized to the error/warning/info/log vocabulary the tool
// filters on; `source` distinguishes a page console call from an uncaught
// exception ('console' | 'exception' | 'log-entry').
export interface LogEntry {
  level: string; text: string; source: string; url: string; line: number; timestamp: number;
}
// What `scroll` reports back so the agent knows where the viewport landed and
// whether more content remains past it (so it can stop paging at the end).
export interface ScrollResult {
  scrollX: number; scrollY: number; moreBelow: boolean; moreRight: boolean;
  url: string; title: string;
}
export interface Request { id: string; method: Method; params: Record<string, unknown>; }
export interface ErrorDetail { code: ErrorCode; message: string; data: Record<string, unknown>; }
export type Response =
  | { id: string; ok: true; result: Record<string, unknown> }
  | { id: string; ok: false; error: ErrorDetail };
export interface Hello {
  event: 'hello'; proto: number; token: string; extension_version: string; browser: string;
}
export interface HelloAck {
  event: 'hello_ack'; proto: number; paired: boolean;
  // ADDITIVE: a daemon released before multi-identity simply does not send
  // these, so an absent `role` MUST be read as 'driver' (behave exactly as
  // before). `authorized_count` defaults to 1 for the same reason. Nothing is
  // added to `Hello` instead: the daemon validates it with extra="forbid", so
  // a new field THERE would be closed 4001 by every already-released daemon.
  role?: 'driver' | 'standby';
  authorized_count?: number;
}
// Daemon -> extension: this link's role CHANGED while it stayed connected
// (a failover, or `lop browser drive`). A separate EVENT rather than a field on
// an existing model, so a released daemon that does not know it ignores the
// frame instead of closing the socket.
export interface Role { event: 'role'; role: 'driver' | 'standby'; }
export interface PairRequest { event: 'pair'; code: string; }
export interface PairResult { event: 'pair_result'; ok: boolean; token: string; message: string; }
export interface Ping { event: 'ping'; }
export interface Pong { event: 'pong'; }
export interface TabClosed { event: 'tab_closed'; tab: string; }
export interface TabUpdate { event: 'tab_update'; tab: string; url: string; title: string; }
export interface AwaitingOrigin { event: 'awaiting_origin'; id: string; origin: string; }
export interface AwaitingOriginCleared { event: 'awaiting_origin_cleared'; id: string; }
export interface Unpair { event: 'unpair'; }
export interface OriginDecision {
  event: 'origin_decision'; origin: string; decision: 'once' | 'site' | 'domain' | 'deny';
}
export type ExtensionEvent =
  | Hello | PairRequest | Pong | TabClosed | TabUpdate | AwaitingOrigin | AwaitingOriginCleared
  | Unpair | OriginDecision;
export type DaemonMessage = HelloAck | PairResult | Ping | Request | Role;
