"""Bounded asset downloads for the image cascade (design §3.5).

One streaming ``GET`` per asset URL with **redirects off** — asset URLs are
the provider's own origins, and following a redirect would let a provider
point the fetch at a host the caller never chose. ``content_type`` comes from
the response header when present, falling back to the payload's own field
(a provider that echoes the type in its result JSON); no retries: each call's
own timeout bounds it, and the rung's overall budget bounds the rung.

The size cap is the one place generated bytes meet a hard ceiling. Generated
media is arbitrarily large, and a download with no cap is a memory-exhaustion
primitive; 32 MiB is generous for a single image on every production model
and small enough that four parallel assets cannot take a host down.
"""

from __future__ import annotations

import logging

import httpx

from local_operator.clients._http import APIError
from local_operator.imagegen import MediaAsset

logger = logging.getLogger(__name__)

#: Per-asset byte ceiling (design §9). A larger payload refuses rather than
#: truncates: a truncated image is not a smaller image, it is a corrupt one.
ARTIFACT_MAX_BYTES = 32 * 1024 * 1024

#: Connect 10 s / read 60 s (design §9): the connect half keeps an unreachable
#: origin from stalling; the read half is sized for tens of megabytes over a
#: slow link.
DOWNLOAD_TIMEOUT = httpx.Timeout(60.0, connect=10.0)


async def download_asset(
    url: str,
    *,
    client: httpx.AsyncClient,
    fallback_content_type: str | None = None,
    width: int | None = None,
    height: int | None = None,
    duration_s: float | None = None,
) -> MediaAsset:
    """Stream one asset into memory under the cap; raise ``APIError`` on failure.

    Runs on the CALLER's client (the rung's injected-client seam), so a test
    with ``httpx.MockTransport`` covers the download path too. A 3xx is
    refused rather than followed (see the module docstring); a missing/odd
    content type falls back to ``fallback_content_type`` when the payload
    carried one, else ``application/octet-stream`` — the attachment contract's
    own default.
    """
    try:
        async with client.stream(
            "GET", url, timeout=DOWNLOAD_TIMEOUT, follow_redirects=False
        ) as response:
            if 300 <= response.status_code < 400:
                raise APIError(
                    f"asset download refused a redirect (HTTP {response.status_code}).",
                    status_code=response.status_code,
                    code="invalid_response",
                )
            if response.status_code >= 400:
                raise APIError(
                    f"asset download refused (HTTP {response.status_code}).",
                    status_code=response.status_code,
                )
            chunks: list[bytes] = []
            total = 0
            async for chunk in response.aiter_bytes():
                total += len(chunk)
                if total > ARTIFACT_MAX_BYTES:
                    raise APIError(
                        f"asset exceeds the {ARTIFACT_MAX_BYTES // (1024 * 1024)} MiB cap.",
                        status_code=None,
                        code="invalid_response",
                    )
                chunks.append(chunk)
            header_type = response.headers.get("content-type", "")
    except httpx.HTTPError as exc:
        raise APIError(f"asset download failed: {exc}", status_code=None, code="network") from exc

    content_type = header_type.split(";")[0].strip()
    if not content_type or content_type == "application/octet-stream":
        fallback = str(fallback_content_type or "").strip()
        if fallback:
            content_type = fallback
    if not content_type:
        content_type = "application/octet-stream"
    return MediaAsset(
        data=b"".join(chunks),
        content_type=content_type,
        source_url=url,
        width=width,
        height=height,
        duration_s=duration_s,
    )
