#!/usr/bin/env python3
"""Regenerate the phone formatter's parity fixture from the TUI's formatter.

WHY THIS FILE EXISTS
--------------------
``local_operator/mobile/web/src/lib/format.ts::formatElapsed`` is a port of
``local_operator/tui/widgets/tool_card.py::format_duration``: the phone's band,
its tool rows and its subagent rows print the same elapsed time the TUI's widget
prints, and two spellings of one number is two answers to one question (design
round 1, D5). Before this fixture the only thing holding the two together was a
hand-verified literal table inside the vitest suite — which pins nothing, because
nothing in the bundle can read the Python and nothing in the Python suite could
read the bundle: a later change to either formatter diverged silently with both
suites green (review round 2, MINOR 4).

The bridge is ONE artifact, ``local_operator/mobile/web/src/lib/format.parity.json``,
read from both sides:

* ``tests/unit/mobile/test_tui_bridge.py`` asserts ``format_duration`` against it;
* ``local_operator/mobile/web/src/lib/format.test.ts`` asserts ``formatElapsed``
  against it.

So a change to either formatter fails a suite in ITS OWN tree, and the only way
to re-align them is to regenerate here and then make the other side agree. The
fixture lives under the web bundle deliberately: that directory is the mobile-web
workflow's own path filter, so regenerating it (a web-path change) is exactly
what makes the vitest half run in CI.

CASES is chosen to cover the whole contract rather than a sample: one
representative per branch, every crossing the form changes at (the second, the
minute, the hour, the day and the 100-day cap), and the ±3s steps around each
crossing, where a rounding or truncation difference shows up first.

    .venv/bin/python scripts/generate_clock_format_parity.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from local_operator.tui.widgets.tool_card import format_duration  # noqa: E402

FIXTURE = (
    Path(__file__).resolve().parents[1] / "local_operator/mobile/web/src/lib/format.parity.json"
)

DAY = 86_400
CROSSINGS = (60, 3_600, DAY, 100 * DAY)

CASES: list[float] = [
    0,
    0.4,
    0.9,
    2.9,
    9.9,
    10.0,
    45,
    59,
    59.4,
    59.9,
    60,
    60.9,
    61,
    119,
    120,
    135,
    3_599,
    3_599.9,
    3_600,
    3_601,
    3_661,
    86_399,
    86_399.9,
    DAY,
    DAY + 1,
    90_000,
    362_400,
    3_602_400,
    8_639_999,
    100 * DAY,
    100 * DAY + 1,
    1_000 * DAY,
]


def build() -> dict[str, object]:
    """The fixture's content: every case with the TUI's own answer for it."""
    ages: set[float] = set(CASES)
    for crossing in CROSSINGS:
        ages.update(float(crossing + step) for step in range(-3, 4))
    return {
        "_": (
            "Generated by scripts/generate_clock_format_parity.py — do not edit by "
            "hand. Read by the vitest suite (format.test.ts) and the Python suite "
            "(tests/unit/mobile/test_tui_bridge.py) so the phone's ported formatter "
            "and the TUI's original cannot drift apart in silence."
        ),
        "cases": [[age, format_duration(age)] for age in sorted(ages)],
    }


def render() -> str:
    """The fixture's exact bytes — one case per line, so a diff names what moved."""
    data = build()
    cases = data["cases"]
    assert isinstance(cases, list)
    title = json.dumps(data["_"], ensure_ascii=False)
    body = ",\n".join(f"  [{json.dumps(age)}, {json.dumps(text)}]" for age, text in cases)
    return f'{{\n "_": {title},\n "cases": [\n{body}\n ]\n}}\n'


def main() -> None:
    """Write the fixture, or (``--check``) prove the committed one came from here.

    ``--check`` is the PROVENANCE half of the pin. Both suites assert the
    fixture's content against their own formatter, which catches drift in a
    formatter but not in the file: a hand edit that rewrote the cases while
    keeping the list longer than the suites' ``>40`` bound would shrink coverage
    silently (review round 3, NIT 1). ``tests/unit/mobile/test_tui_bridge.py``
    makes the same comparison, so CI runs it on every PR; this flag is the human
    path for the same question.
    """
    cases = build()["cases"]
    assert isinstance(cases, list)
    if "--check" in sys.argv[1:]:
        if FIXTURE.read_text() == render():
            print(f"{FIXTURE} is current ({len(cases)} cases)")
            return
        print(f"{FIXTURE} is STALE — regenerate it from this script", file=sys.stderr)
        raise SystemExit(1)
    FIXTURE.write_text(render())
    print(f"wrote {FIXTURE} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
