"""Partition the unit suite into N shards balanced by MEASURED test duration.

Usage:
    python scripts/shard_tests.py --shard I --total N [--out shard_tests.txt]
    python scripts/shard_tests.py --report          # all shards, projected totals

WHY THIS EXISTS
---------------
CI runs the unit suite as five parallel shards under a 20-minute cap. The
split used to be positional -- ``sorted(glob('tests/unit/**/test_*.py'))``
then ``i % 5`` -- which balances the NUMBER of files and ignores what they
cost. Per-file cost in this suite spans four orders of magnitude (a pure
function test is ~1 ms; ``evaluation/runner/test_episode_subprocess.py``
spawns real subprocesses), so an equal file count is not an equal shard.

Measured on 458 files, the positional split projected to:

    shard 0  50.6 test-min | shard 1  19.6 | shard 2  24.1
    shard 3  44.3          | shard 4  81.7            -> 4.16x spread

Against real CI wall times for the same commit (run 34140443526) that
ordering reproduced exactly, heaviest to lightest, 5/5, at r = 0.985. The
heaviest shard ran 19.2 min against the 20-minute cap: about 47 seconds of
headroom.

The cap was not the real problem, though -- the MIGRATION was. Because the
index is positional, adding ONE test file shifts every later file by one and
re-deals the whole suite. The slow cluster therefore hops between shards
(observed moving 3 -> 4 across consecutive green runs), so whichever shard
holds it is ~1 minute from red, and WHICH shard that is depends on an
unrelated file being added somewhere earlier in sort order. A PR adding six
test files came in at 8m46s while a PR adding one blew through the cap and
was reported as a failure with `3693 passed` in its log. Risk was
uncorrelated with what the author actually did, so no author discipline
could mitigate it.

Balancing by duration fixes the consequence rather than the shuffling.
Be precise about what it does and does not do, because the difference
decides whether AGENTS.md's shard-misattribution warning can be retired:

- It does NOT stop files from changing shards. Measured: inserting one file
  moves 326 of 458 files to a different shard (the positional scheme moved
  429). LPT assigns by remaining capacity, so one new weight can cascade.
- It DOES make the reshuffle harmless. Balance is invariant under
  insertion -- +1, +3, +6 and +15 unmeasured files all still produce a
  1.000x spread (44.2, 44.6, 45.1, 46.6 test-min), against 3.8x-4.2x for
  the positional split at the same insertions. There is no longer a
  saturated shard for the slow cluster to migrate INTO, so which shard a
  file lands in stops determining whether the run times out.

So the timeout-by-migration failure is gone, and a shard's runtime is no
longer evidence about who added what. The cross-test-pollution half of the
misattribution warning still stands: a file that changes shards runs beside
different neighbours, and if it leaks or withholds state that is still a
real test-isolation bug. That warning is narrowed by this change, not
retired.

``--dist worksteal`` (in ``addopts``) cannot help here. It rebalances WITHIN
one pytest process; this split happens across five machines before pytest
starts.

THE ALGORITHM
-------------
Longest-processing-time-first (LPT): sort files by descending weight, assign
each to the currently lightest shard. It is the classic greedy makespan
scheduler with a 4/3 worst-case bound, and on this data it lands within
0.1% -- all five shards at 44.1 test-min, a 1.000x spread.

It is DETERMINISTIC, which is a requirement rather than a nicety: the same
commit must produce the same split, or a shard failure is unreproducible.
Two things guarantee that. The file list comes from ``sorted(glob(...))``,
and the tie-break in the sort key is the PATH, so files of equal weight
(including every file sharing the fallback) order identically everywhere.
Shard selection breaks load ties on the lowest index, never on dict order.
No randomness, no filesystem-order dependency, no clock.

STALENESS, AND WHY A MISSING FILE STILL RUNS
--------------------------------------------
The weights live in a committed manifest (``tests/durations.json``)
regenerated by ``scripts/gen_test_durations.py``. A committed manifest drifts
as tests are added, and the alternative designs each drift worse:

- Computing the split from a cached CI artifact makes the partition depend
  on mutable out-of-band state, so the same commit can split two ways and a
  shard failure stops being reproducible. Rejected on determinism.
- Timing the suite inside the workflow to decide the split means running the
  suite to find out how to run the suite. Rejected on cost.

So the manifest is committed, and staleness is handled rather than
prevented. Two properties make it safe:

1. **The file list is globbed, NEVER read from the manifest.** The manifest
   only supplies weights. A file absent from it is still collected and still
   assigned -- it runs with ``fallback_seconds``. A partition that silently
   dropped a test would be far worse than an unbalanced one, and that is the
   single most important invariant in this file. It is guarded by
   ``tests/unit/test_ci_hygiene.py``.
2. **The fallback is pessimistic (p90 of measured files, ~50 s), not the
   median (~1.4 s).** An unknown file is assumed slow, so LPT places it
   early and spreads unknowns across shards instead of stacking them on one.
   The choice is cheap either way: if a brand-new file were secretly the
   slowest in the tree (224 s), the worst shard ends at 47.8 min with a
   median fallback and 47.3 min with a pessimistic one, against 44.1
   balanced -- still far below the 81.7 the positional split produced.

Drift is therefore a gradual loss of balance, never a correctness failure,
and it self-reports: every CI run prints the unmeasured-file count so the
manifest going stale is visible in the log that cares about it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "tests" / "durations.json"
TEST_GLOB = "tests/unit/**/test_*.py"

# Used only if the manifest is missing or unreadable. The partition must
# still be produced -- a broken manifest degrades balance, it never stops
# the suite from running.
DEFAULT_FALLBACK_SECONDS = 50.0


def collect_test_files(repo: Path = REPO) -> list[str]:
    """Every unit test file CI would run, in a deterministic order.

    Deliberately the same expression the positional split used, so the SET
    of tests executed is provably unchanged by this refactor -- only their
    distribution across shards differs.
    """
    return sorted(p.relative_to(repo).as_posix() for p in repo.glob(TEST_GLOB) if p.is_file())


def load_weights(manifest: Path = MANIFEST) -> tuple[dict[str, float], float]:
    """Return (per-file seconds, fallback seconds).

    A missing or malformed manifest is NOT fatal: it degrades to weighting
    every file equally, which reproduces the old positional balance rather
    than failing the run. CI would otherwise go red for a reason unrelated
    to the code under test.
    """
    try:
        data = json.loads(manifest.read_text())
        durations = {str(k): float(v) for k, v in data["durations"].items()}
        fallback = float(data.get("fallback_seconds", DEFAULT_FALLBACK_SECONDS))
        return durations, fallback
    except (OSError, ValueError, KeyError, TypeError):
        return {}, DEFAULT_FALLBACK_SECONDS


def partition(
    files: list[str], weights: dict[str, float], fallback: float, total: int
) -> list[list[str]]:
    """LPT greedy: heaviest first, each onto the currently lightest shard.

    Determinism comes from the two tie-breaks, both of which matter:
    the sort key ends in the path (equal-weight files -- notably every
    unmeasured file sharing `fallback` -- always order the same way), and
    the shard choice breaks a load tie on the lowest index.
    """
    shards: list[list[str]] = [[] for _ in range(total)]
    loads = [0.0] * total
    for path in sorted(files, key=lambda f: (-weights.get(f, fallback), f)):
        target = min(range(total), key=lambda i: (loads[i], i))
        shards[target].append(path)
        loads[target] += weights.get(path, fallback)
    # Restore sort order within a shard: pytest is invoked with this list, and
    # a stable, readable order keeps CI logs diffable between runs.
    return [sorted(s) for s in shards]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--shard", type=int, help="0-based shard index to emit")
    ap.add_argument("--total", type=int, default=5, help="number of shards")
    ap.add_argument("--out", type=Path, help="write the file list here")
    ap.add_argument("--report", action="store_true", help="print projected totals for all shards")
    args = ap.parse_args(argv)

    files = collect_test_files()
    weights, fallback = load_weights()
    shards = partition(files, weights, fallback, args.total)
    unmeasured = [f for f in files if f not in weights]

    if args.report:
        print(
            f"{len(files)} test files, {len(unmeasured)} unmeasured " f"(fallback {fallback:.1f}s)"
        )
        for i, shard in enumerate(shards):
            secs = sum(weights.get(f, fallback) for f in shard)
            print(f"  shard {i}: {len(shard):3d} files  {secs / 60:6.1f} test-min")
        return 0

    if args.shard is None:
        ap.error("--shard is required unless --report is given")
    if not 0 <= args.shard < args.total:
        ap.error(f"--shard must be in [0, {args.total})")

    selected = shards[args.shard]
    projected = sum(weights.get(f, fallback) for f in selected) / 60
    # Printed on every run so a manifest going stale is visible in the log
    # that would suffer from it, rather than only when a shard times out.
    print(
        f"Shard {args.shard + 1}/{args.total}: {len(selected)} test files, "
        f"~{projected:.1f} projected test-min "
        f"({len(unmeasured)} of {len(files)} files unmeasured, "
        f"weighted at the {fallback:.1f}s fallback)"
    )
    if args.out:
        args.out.write_text("\n".join(selected) + "\n")
    else:
        print("\n".join(selected))
    return 0


if __name__ == "__main__":
    sys.exit(main())
