// GENERATED by python -m local_operator.browser_bridge.gen_ts. Do not edit.
// Vendored copy for local-operator-ui: driver/errors.ts (host-free shared policy (chrome.*-free by construction)).
// Source of truth: local-operator local_operator/browser_bridge/protocol.py + gen_ts.py + extension/src/driver/*.ts (10 modules: access-flow.ts, access-queue.ts, ax-compact.ts, deadline.ts, errors.ts, file-transfer-policy.ts, file-transfer.tables.gen.ts, origin-policy.ts, psl.gen.ts, scroll-expressions.ts)
// PROTO_VERSION: 1
// Inputs sha256: 5f72747967b8806c1346a05d061bd0ff90ab069838dabaae21443cc9f0e6a8cd
// An INPUT hash, never a git SHA: a stamp over commits would go red on every
// commit that touched nothing this generator reads, and a gate that cries wolf
// gets deleted. Regenerate with `python -m local_operator.browser_bridge.gen_ts`;
// `--bundle-out DIR` is the same command pointed at another tree, which is how
// local-operator-ui's sync script generates its own checkout.
/**
 * The one typed bridge failure, in a module of its own.
 *
 * This looks like an unnecessary indirection and is not one. `cdp.ts` owns
 * `BridgeCommandError` historically, but it also registers a
 * `chrome.debugger.onDetach` listener at MODULE level, so any module that
 * imports the class from `./cdp` drags the whole CDP layer into its bundle.
 * That was invisible until `settle.ts` (the per-call `deadline` helper) and
 * `state.ts` (which bounds its storage awaits) started needing the class in
 * common: the resulting `cdp → settle → cdp` cycle reordered module evaluation
 * and made a storage-only bundle touch `chrome.debugger` — which the pure
 * storage/grouping unit harnesses do not provide, so they failed at load time
 * with `Cannot read properties of undefined (reading 'onDetach')`.
 *
 * Keeping the error value here breaks the cycle at its root: `errors.ts`
 * imports nothing, `settle.ts` and `state.ts` reach the class without reaching
 * `cdp.ts`, and `cdp.ts` still re-exports it so every existing
 * `from "./cdp"` import site keeps working unchanged.
 */
export class BridgeCommandError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly data: Record<string, unknown> = {},
  ) {
    super(message);
  }
}
