"""GENERATED by scripts/i18n/generate.py — do not edit by hand.

Regenerate with `.venv/bin/python scripts/i18n/generate.py`; CI rejects
drift (`generate.py --check`). The one function per message key is the
shape RFC §2.4 proved: a mistyped key or kwarg fails pyright.
"""

from __future__ import annotations
