"""The shipped seed revision ledger must describe exactly the packaged history.

``local_operator/agent_seeds/seed_revisions.json`` is the proof behind #2060's
startup update pass: every text a built-in seed ever SHIPPED, oldest first per
seed, so a row whose canonical vector equals an entry is provably an unedited
published revision — and the entry's POSITION is what decides behind from
ahead (version strings repeat; aida shipped four ``1.0.0`` builds).

It is generated by ``scripts/gen_agent_seed_revisions.py`` and committed, and
it holds only as long as these properties do:

* **Byte identity, not field comparison.** Normal-mode regeneration must
  reproduce the committed bytes exactly — the manifest test's discipline, for
  the same reason: a new field, a reordering or a stale hash would otherwise
  pass review. A no-op against a clean tree, so reviewers and CI can run it.
* **``--check`` without git.** The CI gate validates schema, order, uniqueness
  and every seed's tail == the packaged starter on a ``fetch-depth 2``
  checkout where history does not exist; it must never write.
* **The deep check: every entry's sha really carries its text**, skipped when
  the commits are not resolvable (shallow CI) and run locally.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess

import pytest

import local_operator.agent_profiles as agent_profiles
from local_operator.agent_profiles import (
    SEED_REVISIONS_NAME,
    SEEDS_DIR,
    _split_frontmatter,
    list_seeds,
    load_seed,
    load_seed_revisions,
    match_seed_revision,
    seed_revision_vector,
)
from scripts import gen_agent_seed_revisions as generator

LEDGER_PATH = SEEDS_DIR / SEED_REVISIONS_NAME


def _git(*args: str) -> subprocess.CompletedProcess[bytes] | None:
    try:
        return subprocess.run(
            ["git", "-C", str(generator.REPO), *args], capture_output=True, text=False
        )
    except OSError:  # pragma: no cover - no git on PATH
        return None


def _deep_history_available() -> bool:
    """Whether the commits and tags this file's deep checks need are present."""

    tag = _git("tag", "--list", "v0.63.5")
    if tag is None or tag.returncode != 0 or not tag.stdout.strip():
        return False
    return all(
        generator._history_available(f"local_operator/agent_seeds/{name}.md")
        for name in list_seeds()
    )


def _batch_blobs(specs: list[str]) -> dict[str, str | None]:
    """Fetch many ``<ref>:<path>`` blobs through ONE ``git cat-file --batch``.

    One process, one pipe: the naive subprocess-per-blob spelling of the two
    deep tests below cost ~100 s on the reference host (560 ``git show``
    invocations for the tag sweep alone), which is exactly the kind of suite
    weight AGENTS.md's sharding rules exist to keep bounded. A missing object
    answers ``None`` (an entry/tag whose commit is not in this clone is
    skipped, never failed).
    """

    if not specs:
        return {}
    try:
        proc = subprocess.Popen(
            ["git", "-C", str(generator.REPO), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
    except OSError:  # pragma: no cover - no git on PATH
        return {spec: None for spec in specs}
    assert proc.stdin is not None and proc.stdout is not None
    proc.stdin.write("".join(f"{spec}\n" for spec in specs).encode("utf-8"))
    proc.stdin.close()
    results: dict[str, str | None] = {}
    out = proc.stdout
    for spec in specs:
        header = out.readline().decode("utf-8", "replace").strip()
        if not header or header.endswith(" missing"):
            results[spec] = None
            continue
        size = int(header.split()[2])
        results[spec] = out.read(size).decode("utf-8", "replace")
        out.read(1)  # the record's trailing newline
    out.close()
    proc.wait(timeout=30)
    return results


def test_regeneration_reproduces_the_committed_bytes() -> None:
    """Normal-mode regeneration is a no-op — the check that makes it generated.

    The ledger's append rule keys on the packaged text, so a clean tree (every
    seed committed, every tail matching) renders the committed bytes with no
    git reads at all; that is what lets CI run this on a shallow checkout.
    """

    assert generator.render() == LEDGER_PATH.read_text(encoding="utf-8"), (
        "the committed ledger is stale; regenerate it with: "
        ".venv/bin/python scripts/gen_agent_seed_revisions.py"
    )


def test_check_passes_on_the_committed_file_and_never_writes(tmp_path, capsys) -> None:
    """``--check`` is the CI/reviewer gate: loud on stale, silent on the file."""

    assert generator.main(["--check"]) == 0

    # Derive the stale copy from the real one so the mutation is a real
    # violation (a seed's TAIL no longer equals the packaged starter), not a
    # cosmetic byte difference the schema checks would rightly ignore.
    committed = LEDGER_PATH.read_text(encoding="utf-8")
    payload = json.loads(committed)
    payload["seeds"]["aida"][-1]["instructions_sha256"] = "0" * 64
    stale = tmp_path / SEED_REVISIONS_NAME
    stale.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    assert stale.read_text(encoding="utf-8") != committed

    assert generator.main(["--check", "--out", str(stale)]) == 1
    assert stale.read_text(encoding="utf-8") != committed, "--check must not rewrite"


def test_bootstrap_refuses_a_marked_shallow_clone_and_never_truncates(
    tmp_path, monkeypatch
) -> None:
    """QA round 1, Q3 / agent review round 1, R1-4, in the repro's shape.

    A ``--depth 1`` clone answers ``--is-shallow-repository`` true; the
    pre-fix bootstrap walked its single graft commit, wrote a 10-revision
    ledger over the committed 65, and ``--check`` then PASSED on the
    truncated file. Now the marker refuses first — writes NOTHING — and
    ``--allow-shallow`` is the explicit escape hatch, reserved for a clone
    known to be complete despite the marker. Independently, a bootstrap walk
    that would shrink an existing target refuses regardless of door.

    ``--depth`` is honoured here because the source is addressed as a
    ``file://`` URL, which disables git's local-clone path where the flag
    would otherwise be ignored with a warning.
    """

    clone = tmp_path / "shallow"
    subprocess.run(
        ["git", "clone", "--depth", "1", "--single-branch", generator.REPO.as_uri(), str(clone)],
        check=True,
        capture_output=True,
    )
    shallow = subprocess.run(
        ["git", "-C", str(clone), "rev-parse", "--is-shallow-repository"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    assert shallow == "true"

    seeds_dir = clone / "local_operator" / "agent_seeds"
    monkeypatch.setattr(generator, "REPO", clone)
    monkeypatch.setattr(agent_profiles, "SEEDS_DIR", seeds_dir)

    # ``--check`` runs without history, as CI does on fetch-depth 2.
    assert generator.main(["--check"]) == 0

    committed = (seeds_dir / SEED_REVISIONS_NAME).read_bytes()

    with pytest.raises(SystemExit) as refusal:
        generator.main(["--bootstrap-from-git"])
    assert "--allow-shallow" in str(refusal.value)
    assert (seeds_dir / SEED_REVISIONS_NAME).read_bytes() == committed

    # The override proceeds — but only to a FRESH target: the walk's output
    # (the clone's single commit) must never overwrite the full ledger.
    out = tmp_path / "boot.json"
    assert generator.main(["--bootstrap-from-git", "--allow-shallow", "--out", str(out)]) == 0
    assert json.loads(out.read_text(encoding="utf-8"))["seeds"]

    with pytest.raises(SystemExit) as truncation:
        generator.main(["--bootstrap-from-git", "--allow-shallow"])
    assert "refusing to truncate" in str(truncation.value)
    assert (seeds_dir / SEED_REVISIONS_NAME).read_bytes() == committed


def test_every_seed_tail_equals_the_packaged_starter() -> None:
    """The runtime's auto-apply guard, asserted per seed without git."""

    revisions = load_seed_revisions()
    for name in list_seeds():
        seed = load_seed(name)
        assert seed is not None, name
        matched = match_seed_revision(name, seed, revisions=revisions)
        assert matched is not None, f"{name}: packaged text is not in the ledger"
        assert matched[0] == len(revisions[name]) - 1, f"{name}: packaged text is not the tail"


def test_the_same_day_aida_builds_are_distinct_ordered_entries() -> None:
    """The two 1.0.0 builds that shipped in one release, as separate entries.

    This is the whole direction argument in miniature: ``8b24f2b477`` and
    ``26fbd695b`` carry the SAME version string and different text, so being
    able to place them in ledger order is what keeps an older build's ``lop``
    from flipping a newer row back.
    """

    entries = load_seed_revisions()["aida"]
    assert entries[0].sha.startswith("8b24f2b477")
    assert entries[1].sha.startswith("26fbd695b")
    assert entries[0].version == entries[1].version == "1.0.0"
    assert entries[0].instructions_sha256 != entries[1].instructions_sha256


def test_the_ledger_covers_every_release_shipped_text() -> None:
    """Every text a release tag carried is placeable in the ledger.

    A user's row can hold ANY text that ever shipped, and the startup pass can
    only re-prove the ones the ledger can name — the manager's probe measured
    43 such texts across 10 seeds (aida 9). Skipped where the tags are not
    fetched (shallow CI).
    """

    tags_probe = _git("tag", "--sort=creatordate")
    if tags_probe is None or tags_probe.returncode != 0 or not _deep_history_available():
        pytest.skip("full tags/history not available (shallow checkout)")

    tags = [
        t
        for t in tags_probe.stdout.decode("utf-8", "replace").split()
        if re.fullmatch(r"v0\.\d+\.\d+", t)
    ]
    assert "v0.63.5" in tags, "the first stamp-shipping tag must be fetched for this check"
    tags = tags[tags.index("v0.63.5") :]
    specs = {
        f"{tag}:local_operator/agent_seeds/{name}.md": (tag, name)
        for tag in tags
        for name in list_seeds()
    }
    blobs = _batch_blobs(sorted(specs))
    revisions = load_seed_revisions()
    seen: dict[str, set[tuple[object, ...]]] = {}
    for spec, text in blobs.items():
        if text is None:
            continue
        _tag, name = specs[spec]
        profile = agent_profiles._profile_from_text(name, text)
        vector = seed_revision_vector(profile)
        identity = (
            hashlib.sha256(vector[0].encode("utf-8")).hexdigest(),
            vector[1],
            vector[2],
            vector[3],
            vector[4],
        )
        seen.setdefault(name, set()).add(identity)
    missing = []
    for name, identities in seen.items():
        entry_identities = {
            (
                entry.instructions_sha256,
                entry.description,
                entry.tools,
                entry.effort,
                entry.delegate,
            )
            for entry in revisions[name]
        }
        for identity in identities:
            if identity not in entry_identities:
                missing.append((name, identity[1]))
    assert not missing, f"release texts missing from the ledger: {missing}"


def test_every_entry_describes_the_blob_it_names() -> None:
    """THE deep honesty check: entry hashes, verified against git, entry by entry.

    ``--check`` cannot do this on a shallow checkout, so it runs where the
    commits are resolvable and skips where they are not. An entry whose commit
    cannot be resolved is skipped, not failed (a future squash-rewrite of old
    history must not turn this into a mystery failure) — but every resolvable
    entry must recompute EXACTLY: hash, routing text, tools, effort, delegate,
    and the carried (non-identifying) class.
    """

    if not _deep_history_available():
        pytest.skip("full history not available (shallow checkout)")
    revisions = load_seed_revisions()
    specs = {
        f"{entry.sha}:local_operator/agent_seeds/{name}.md": (name, entry)
        for name in list_seeds()
        for entry in revisions[name]
    }
    blobs = _batch_blobs(sorted(specs))
    text: str | None
    for spec, text in blobs.items():
        if text is None:
            continue  # a commit this clone cannot resolve is skipped, not failed
        name, entry = specs[spec]
        profile = agent_profiles._profile_from_text(name, text)
        vector = seed_revision_vector(profile)
        assert hashlib.sha256(vector[0].encode("utf-8")).hexdigest() == entry.instructions_sha256, (
            name,
            entry.sha,
        )
        assert vector[1] == entry.description, (name, entry.sha)
        assert vector[2] == entry.tools, (name, entry.sha)
        assert vector[3] == entry.effort, (name, entry.sha)
        assert vector[4] == entry.delegate, (name, entry.sha)
        raw_class = _split_frontmatter(text)[0].get("class")
        declared = (
            agent_profiles.normalize_action_class(raw_class)
            if raw_class is not None and str(raw_class).strip()
            else None
        )
        assert declared == entry.action_class, (name, entry.sha)

        # The matcher must place the entry's own text — exhaustively, for
        # every entry (the manager's probe texts) — at an index whose
        # identity is this entry's.
        matched = match_seed_revision(name, profile)
        assert matched is not None, (name, entry.sha)
        landed = matched[1]
        assert (
            landed.instructions_sha256,
            landed.description,
            landed.tools,
            landed.effort,
            landed.delegate,
        ) == (
            entry.instructions_sha256,
            entry.description,
            entry.tools,
            entry.effort,
            entry.delegate,
        ), (
            name,
            entry.sha,
        )
